#ifndef __ATTR_ID_H__
#define __ATTR_ID_H__

#include <stdint.h>
#include <map>

enum PlayerAttrId
{
	PLAYER_ATTR_MAXHP = 1, //生命值上限
	PLAYER_ATTR_HP = 2, //生命
	PLAYER_ATTR_ATTACK = 3, //攻击
	PLAYER_ATTR_DEFENSE = 4, //防御
	PLAYER_ATTR_ATK_METAL = 5, //金攻
	PLAYER_ATTR_ATK_WOOD = 6, //木攻
	PLAYER_ATTR_ATK_WATER = 7, //水攻
	PLAYER_ATTR_ATK_FIRE = 8, //火攻
	PLAYER_ATTR_ATK_EARTH = 9, //土攻
	PLAYER_ATTR_DEF_METAL = 10, //金抗
	PLAYER_ATTR_DEF_WOOD = 11, //木抗
	PLAYER_ATTR_DEF_WATER = 12, //水抗
	PLAYER_ATTR_DEF_FIRE = 13, //火抗
	PLAYER_ATTR_DEF_EARTH = 14, //土抗
	PLAYER_ATTR_DODGE = 15, //闪避
	PLAYER_ATTR_HIT = 16, //命中
	PLAYER_ATTR_CRIT = 17, //暴击
	PLAYER_ATTR_CRIT_DEF = 18, //暴抗
	PLAYER_ATTR_CRT_DMG = 19, //暴击伤害
	PLAYER_ATTR_CRT_DMG_DEF = 20, //暴击免伤
	PLAYER_ATTR_MOVE_SPEED = 21, //移动速度
	PLAYER_ATTR_HP_RECOVER = 22, //回血速度
	PLAYER_ATTR_CURE = 23, //治疗强度
	PLAYER_ATTR_CURE_ADD = 24, //治疗加成
	PLAYER_ATTR_DMG_ADD = 25, //伤害加成
	PLAYER_ATTR_DMG_DEF = 26, //伤害减免
	PLAYER_ATTR_DMG_ADD_PE = 27, //惩戒
	PLAYER_ATTR_DMG_DEF_PP = 28, //豁免
	PLAYER_ATTR_STUN = 29, //眩晕
	PLAYER_ATTR_SLOW = 30, //迟缓
	PLAYER_ATTR_CHAOS = 31, // 混乱
	PLAYER_ATTR_POISON = 32, //中毒
	PLAYER_ATTR_VAMPIRE = 33, //吸血
	PLAYER_ATTR_BOUNCE = 34, //反弹
	PLAYER_ATTR_HIT_REPEL = 35, //击退
	PLAYER_ATTR_HIT_FLY = 36, //击飞
	PLAYER_ATTR_STUN_DEF = 37, //眩晕抗性
	PLAYER_ATTR_SLOW_DEF = 38, //迟缓抗性
	PLAYER_ATTR_CHAOS_DEF = 39, //混乱抗性
	PLAYER_ATTR_POISON_DEF = 40, //中毒抗性
	PLAYER_ATTR_VAMPIRE_DEF = 41, //吸血抗性
	PLAYER_ATTR_BOUNCE_DEF = 42, //反弹抗性
	PLAYER_ATTR_HIT_REPEL_DEF = 43, //击退抗性
	PLAYER_ATTR_HIT_FLY_DEF = 44, //击飞抗性
	PLAYER_ATTR_LEVEL = 45, //等级
	PLAYER_ATTR_FLY_SPEED = 46, //飞行速度
	PLAYER_ATTR_ZHENYING = 47, //阵营
	PLAYER_ATTR_PK_TYPE = 48, //pk模式 0和平,1阵营,2杀戮
	PLAYER_ATTR_FIGHT_MAX,        //战斗相关的最大属性ID

	PLAYER_ATTR_JOB = 51, //职业
	PLAYER_ATTR_EXP = 53, //经验

	PLAYER_ATTR_GOLD = 54, //元宝
	PLAYER_ATTR_BIND_GOLD = 55, //绑定元宝
	PLAYER_ATTR_COIN = 56, //银两
	PLAYER_ATTR_HEAD = 57, //头像
	PLAYER_ATTR_CLOTHES = 58, //衣服
	PLAYER_ATTR_CLOTHES_COLOR_UP = 59, //衣服颜色
	PLAYER_ATTR_HAT = 60, //帽子
	PLAYER_ATTR_HAT_COLOR = 61, //帽子颜色
	PLAYER_ATTR_CLOTHES_COLOR_DOWN = 62, //衣服颜色

	PLAYER_ATTR_RELIVE_TYPE1 = 63, //原地复活，类型1
	PLAYER_ATTR_RELIVE_TYPE2 = 64, //原地复活，类型2

	PLAYER_ATTR_WEAPON = 65, //武器外形
	PLAYER_ATTR_FIGHTING_CAPACITY = 66, //战斗力
	PLAYER_ATTR_CUR_HORSE = 67, //当前坐骑
	PLAYER_ATTR_ON_HORSE_STATE = 68, //乘骑状态 0:下坐骑 1:上坐骑
	PLAYER_ATTR_ZHENQI = 69, //真气

	PLAYER_ATTR_MURDER = 70, //杀戮值
	PLAYER_ATTR_COURAGE_GOLD = 71, //勇气币
	PLAYER_ATTR_BAGUA = 72, //八卦牌
	PLAYER_ATTR_ACTIVENESS = 73, //活动活跃度
	PLAYER_ATTR_REGION_ID = 74, //区域ID
	PLAYER_ATTR_CHIVALRY = 75, //侠义值
	PLAYER_ATTR_ENERGY = 77, //精力值
	PLAYER_ATTR_BRAVE = 78, //勇武值
	
	PLAYER_ATTR_ITEM_HP_CD = 79, //加血药剂CD
	PLAYER_ATTR_ITEM_HP_POOL_CD = 80, //血池药品CD	
	PLAYER_ATTR_PARTNER_FIGHT = 81, //伙伴出战状态
	PLAYER_ATTR_PARTNER_PRECEDENCE = 82, //主战伙伴是否优先出战
	PLAYER_ATTR_PARTNER_ANGER = 83, //伙伴怒气
	PLAYER_ATTR_WEAPON_COLOR = 84, //武器外形

	PLAYER_ATTR_MAX
};

typedef std::map<uint32_t, double> AttrMap;
#define MAX_BUFF_FIGHT_ATTR (PLAYER_ATTR_MOVE_SPEED + 1)
#define MAX_PARTNER_ATTR (PLAYER_ATTR_FIGHTING_CAPACITY + 1)
#endif
