 #ifndef __ATTR_ID_H__
#define __ATTR_ID_H__

#include <stdint.h>
#include <map>

enum PlayerAttrId
{
	PLAYER_ATTR_HP = 1, //生命
	PLAYER_ATTR_MAXHP = 2, //生命值上限
	PLAYER_ATTR_ATTACK = 3, //攻击
//	PLAYER_ATTR_DEFENSE = 4, //防御
	PLAYER_ATTR_DFWUDEL = 4, //忽略全抗
	PLAYER_ATTR_ATK_METAL = 5, //金攻
	PLAYER_ATTR_ATK_WOOD = 6, //木攻
	PLAYER_ATTR_ATK_WATER = 7, //水攻
	PLAYER_ATTR_ATK_FIRE = 8, //火攻
	PLAYER_ATTR_ATK_EARTH = 9, //土攻
	PLAYER_ATTR_DEF_METAL = 10, //金抗
	PLAYER_ATTR_DEF_WOOD = 11, //木抗
	PLAYER_ATTR_DEF_WATER = 12, //水抗
	PLAYER_ATTR_DEF_FIRE = 13, //火抗
	PLAYER_ATTR_DEF_EARTH = 14, //土抗
	PLAYER_ATTR_DODGE = 15, //闪避
	PLAYER_ATTR_HIT = 16, //命中
	PLAYER_ATTR_CRIT = 17, //暴击
	PLAYER_ATTR_CRIT_DEF = 18, //暴抗
	PLAYER_ATTR_CRT_DMG = 19, //暴击伤害
	PLAYER_ATTR_CRT_DMG_DEF = 20, //暴击免伤
	PLAYER_ATTR_MOVE_SPEED = 21, //移动速度
//#define MAX_BUFF_FIGHT_ATTR (PLAYER_ATTR_MOVE_SPEED + 1)
	
	PLAYER_ATTR_DODGEDF = 22, //	忽略闪避
	PLAYER_ATTR_DIZZY = 23, //	眩晕几率
	PLAYER_ATTR_SLOW = 24, //	迟缓几率
	PLAYER_ATTR_MABI = 25, //	麻痹几率
	PLAYER_ATTR_HURT = 26, //	受伤几率
	PLAYER_ATTR_CAN = 27, //	致残几率
	PLAYER_ATTR_DIZZYDF = 28, //	抗眩晕几率
	PLAYER_ATTR_SLOWDF = 29, //	抗迟缓几率
	PLAYER_ATTR_MABIDF = 30, //	抗麻痹几率
	PLAYER_ATTR_HURTDF = 31, //	抗受伤几率
	PLAYER_ATTR_CANDF = 32, //	抗致残几率
	PLAYER_ATTR_PVPAT = 33, // 穿刺
	PLAYER_ATTR_PVPDF = 34, //霸体
	PLAYER_ATTR_REGION_ID = 35, //区域ID
	
// 	PLAYER_ATTR_DIZZYTIME = 33, //	眩晕时间
// 	PLAYER_ATTR_SLOWTIME = 34, // 	迟缓时间
// 	PLAYER_ATTR_MABITIME = 35, // 	麻痹时间
// 	PLAYER_ATTR_HURTTIME = 36, // 	受伤时间
// 	PLAYER_ATTR_CANTIME = 37, //	致残时间
// 	PLAYER_ATTR_DIZZYTIMEDF = 38, //	抗眩晕时间
// 	PLAYER_ATTR_SLOWTIMEDF = 39, // 	抗迟缓时间
// 	PLAYER_ATTR_MABITIMEDF = 40, // 	抗麻痹时间
// 	PLAYER_ATTR_HURTTIMEDF = 41, // 	抗受伤时间
// 	PLAYER_ATTR_CANTIMEDF = 42, // 	抗致残时间
// 	PLAYER_ATTR_DEEFFDF = 43, //	抗负面效果几率
// 	PLAYER_ATTR_DETIMEDF = 44, //	抗负面效果时间
// 	PLAYER_ATTR_HP_RECOVER = 22, //回血速度
// 	PLAYER_ATTR_CURE = 23, //治疗强度
// 	PLAYER_ATTR_CURE_ADD = 24, //治疗加成
// 	PLAYER_ATTR_DMG_ADD = 25, //伤害加成
// 	PLAYER_ATTR_DMG_DEF = 26, //伤害减免
// 	PLAYER_ATTR_DMG_ADD_PE = 27, //惩戒
// 	PLAYER_ATTR_DMG_DEF_PP = 28, //豁免
//	PLAYER_ATTR_STUN = 29, //眩晕
//	PLAYER_ATTR_SLOW = 30, //迟缓
// 	PLAYER_ATTR_CHAOS = 31, // 混乱
// 	PLAYER_ATTR_POISON = 32, //中毒
// 	PLAYER_ATTR_VAMPIRE = 33, //吸血
// 	PLAYER_ATTR_BOUNCE = 34, //反弹
// 	PLAYER_ATTR_HIT_REPEL = 35, //击退
// 	PLAYER_ATTR_HIT_FLY = 36, //击飞
// 	PLAYER_ATTR_STUN_DEF = 37, //眩晕抗性
// 	PLAYER_ATTR_SLOW_DEF = 38, //迟缓抗性
// 	PLAYER_ATTR_CHAOS_DEF = 39, //混乱抗性
// 	PLAYER_ATTR_POISON_DEF = 40, //中毒抗性
// 	PLAYER_ATTR_VAMPIRE_DEF = 41, //吸血抗性
// 	PLAYER_ATTR_BOUNCE_DEF = 42, //反弹抗性
// 	PLAYER_ATTR_HIT_REPEL_DEF = 43, //击退抗性
// 	PLAYER_ATTR_HIT_FLY_DEF = 44, //击飞抗性
	PLAYER_ATTR_LEVEL = 45, //等级
	PLAYER_ATTR_FLY_SPEED = 46, //飞行速度
	PLAYER_ATTR_ZHENYING = 47, //阵营
	PLAYER_ATTR_PK_TYPE = 48, //pk模式 0和平,1阵营,2杀戮
	PLAYER_ATTR_FIGHT_MAX,        //战斗相关的最大属性ID

	PLAYER_ATTR_FIGHTING_CAPACITY = 50, //战斗力

	PLAYER_ATTR_JOB = 51, //职业
	PLAYER_ATTR_SILVER = 52, //银两
	PLAYER_ATTR_EXP = 53, //经验

	PLAYER_ATTR_GOLD = 54, //元宝
	PLAYER_ATTR_BIND_GOLD = 55, //绑定元宝
	PLAYER_ATTR_COIN = 56, //银票
	PLAYER_ATTR_HEAD = 57, //头像
	PLAYER_ATTR_CLOTHES = 58, //衣服
	PLAYER_ATTR_CLOTHES_COLOR_UP = 59, //衣服颜色
	PLAYER_ATTR_HAT = 60, //帽子
	PLAYER_ATTR_HAT_COLOR = 61, //帽子颜色
	PLAYER_ATTR_CLOTHES_COLOR_DOWN = 62, //衣服颜色

	PLAYER_ATTR_RELIVE_TYPE1 = 63, //原地复活，类型1
	PLAYER_ATTR_RELIVE_TYPE2 = 64, //原地复活，类型2

	PLAYER_ATTR_WEAPON = 65, //武器外形
	
	PLAYER_ATTR_CUR_HORSE = 67, //当前坐骑
	PLAYER_ATTR_ON_HORSE_STATE = 68, //乘骑状态 0:下坐骑 1:上坐骑
	PLAYER_ATTR_ZHENQI = 69, //真气

	PLAYER_ATTR_MURDER = 70, //杀戮值
	PLAYER_ATTR_GONGXUN = 71, //功勋
	PLAYER_ATTR_BAGUA = 72, //八卦牌
	PLAYER_ATTR_ACTIVENESS = 73, //活动活跃度

//	PLAYER_ATTR_CHIVALRY = 75, //侠义值
	PLAYER_ATTR_ENERGY = 77, //精力值
	PLAYER_ATTR_BRAVE = 78, //勇武值
	
	PLAYER_ATTR_ITEM_HP_CD = 79, //加血药剂CD
	PLAYER_ATTR_ITEM_HP_POOL_CD = 80, //血池药品CD	
	PLAYER_ATTR_PARTNER_FIGHT = 81, //伙伴出战状态
	PLAYER_ATTR_PARTNER_PRECEDENCE = 82, //主战伙伴是否优先出战
	PLAYER_ATTR_PARTNER_ANGER = 83, //伙伴怒气
	PLAYER_ATTR_WEAPON_COLOR = 84, //武器外形
//	PLAYER_ATTR_TILV = 85, // 	体质成长
//	PLAYER_ATTR_LILV = 86, // 	力量成长
//	PLAYER_ATTR_MINLV = 87, //	敏捷成长
//	PLAYER_ATTR_LINGLV = 88, //	灵巧成长
	PLAYER_ATTR_TI = 89, //		 体质
	PLAYER_ATTR_LI = 90, // 	力量
	PLAYER_ATTR_MIN = 91, //	敏捷
	PLAYER_ATTR_LING = 92, //	灵巧
	PLAYER_ATTR_HEALTHPRO = 93, // 	基础生命加成
	PLAYER_ATTR_ATTACKPRO = 94, // 	基础攻击加成
	PLAYER_ATTR_DFWU = 95, //	全系抗性
	PLAYER_ATTR_ALLEFF = 96, //	属性效果几率
	PLAYER_ATTR_ALLEFFDF = 97, //	抗属性效果几率
//#define MAX_PARTNER_ATTR (PLAYER_ATTR_ALLEFFDF + 1)
//	PLAYER_ATTR_ALLTIME = 98, //	属性效果时间
//	PLAYER_ATTR_AllTimeDf = 99, //	抗属性效果时间
	PLAYER_ATTR_SHENGWANG = 100, //声望
	PLAYER_ATTR_XUEJING = 101, //血晶
	PLAYER_ATTR_LINGSHI = 102, //灵石

	PLAYER_ATTR_TITLE = 103, //称号
	PLAYER_ATTR_EXP_ZHENQI = 104, //经验转换的真气

	PLAYER_ATTR_MAX
};

typedef std::map<uint32_t, double> AttrMap;
#define MAX_BUFF_FIGHT_ATTR (PLAYER_ATTR_MOVE_SPEED + 1)
#define MAX_PARTNER_ATTR (PLAYER_ATTR_ALLEFFDF + 1)
#endif
