local ShopListTable = {
	[280001011] = {
		['ID'] = 280001011,	--索引
		['ShopType'] = 1,	--商城类型
		['ShopType1'] = 1,	--商城小类型
		['TabName'] = '热销商品',	--页签名称
		['GroupingName'] = '热销商品',	--分组名称
		['OpenConditionType'] = 0,	--开放条件类型
		['OpenCondition'] = '',	--开放条件
		['StartTime'] = 0,	--开始时间
		['EndTime'] = 0,	--结束时间
		['ConsumptionType'] = 2,	--货币类型
		['TabDescribe'] = ''	--页签说明
		},
	[280001012] = {
		['ID'] = 280001012,
		['ShopType'] = 1,
		['ShopType1'] = 2,
		['TabName'] = '大陆杂货',
		['GroupingName'] = '大陆杂货',
		['OpenConditionType'] = 0,
		['OpenCondition'] = '',
		['StartTime'] = 0,
		['EndTime'] = 0,
		['ConsumptionType'] = 2,
		['TabDescribe'] = ''
		},
	[280001013] = {
		['ID'] = 280001013,
		['ShopType'] = 1,
		['ShopType1'] = 3,
		['TabName'] = '限时抢购',
		['GroupingName'] = '限时抢购',
		['OpenConditionType'] = 0,
		['OpenCondition'] = '',
		['StartTime'] = 1483545600,
		['EndTime'] = 1483977600,
		['ConsumptionType'] = 2,
		['TabDescribe'] = ''
		},
	[280001014] = {
		['ID'] = 280001014,
		['ShopType'] = 1,
		['ShopType1'] = 4,
		['TabName'] = '限购商店',
		['GroupingName'] = '限购商店',
		['OpenConditionType'] = 0,
		['OpenCondition'] = '',
		['StartTime'] = 0,
		['EndTime'] = 0,
		['ConsumptionType'] = 2,
		['TabDescribe'] = ''
		},
	[280001015] = {
		['ID'] = 280001015,
		['ShopType'] = 1,
		['ShopType1'] = 5,
		['TabName'] = '八卦商店',
		['GroupingName'] = '八卦商店',
		['OpenConditionType'] = 0,
		['OpenCondition'] = '',
		['StartTime'] = 0,
		['EndTime'] = 0,
		['ConsumptionType'] = 2,
		['TabDescribe'] = ''
		},
	[280003011] = {
		['ID'] = 280003011,
		['ShopType'] = 3,
		['ShopType1'] = 1,
		['TabName'] = '帮贡商店',
		['GroupingName'] = '帮贡商店',
		['OpenConditionType'] = 0,
		['OpenCondition'] = '',
		['StartTime'] = 0,
		['EndTime'] = 0,
		['ConsumptionType'] = 5,
		['TabDescribe'] = '使用帮贡可兑换下列物品'
		},
	[280003021] = {
		['ID'] = 280003021,
		['ShopType'] = 3,
		['ShopType1'] = 2,
		['TabName'] = '竞技场\n商店',
		['GroupingName'] = '青铜商店',
		['OpenConditionType'] = 1,
		['OpenCondition'] = '竞技场等级达到青铜',
		['StartTime'] = 0,
		['EndTime'] = 0,
		['ConsumptionType'] = 6,
		['TabDescribe'] = '使用竞技场积分可兑换下列物品'
		},
	[280003022] = {
		['ID'] = 280003022,
		['ShopType'] = 3,
		['ShopType1'] = 2,
		['TabName'] = '竞技场\n商店',
		['GroupingName'] = '白银商店',
		['OpenConditionType'] = 2,
		['OpenCondition'] = '竞技场等级达到白银',
		['StartTime'] = 0,
		['EndTime'] = 0,
		['ConsumptionType'] = 6,
		['TabDescribe'] = '使用竞技场积分可兑换下列物品'
		},
	[280003023] = {
		['ID'] = 280003023,
		['ShopType'] = 3,
		['ShopType1'] = 2,
		['TabName'] = '竞技场\n商店',
		['GroupingName'] = '黄金商店',
		['OpenConditionType'] = 3,
		['OpenCondition'] = '竞技场等级达到黄金',
		['StartTime'] = 0,
		['EndTime'] = 0,
		['ConsumptionType'] = 6,
		['TabDescribe'] = '使用竞技场积分可兑换下列物品'
		},
	[280003031] = {
		['ID'] = 280003031,
		['ShopType'] = 3,
		['ShopType1'] = 3,
		['TabName'] = '侠义值\n商店',
		['GroupingName'] = '侠义值\n商店',
		['OpenConditionType'] = 0,
		['OpenCondition'] = '',
		['StartTime'] = 0,
		['EndTime'] = 0,
		['ConsumptionType'] = 7,
		['TabDescribe'] = '使用侠义值可兑换下列物品'
		},
	[280003041] = {
		['ID'] = 280003041,
		['ShopType'] = 3,
		['ShopType1'] = 4,
		['TabName'] = 'VIP商店',
		['GroupingName'] = 'VIP1商店',
		['OpenConditionType'] = 1,
		['OpenCondition'] = 'VIP等级达到1级',
		['StartTime'] = 0,
		['EndTime'] = 0,
		['ConsumptionType'] = 2,
		['TabDescribe'] = ''
		},
	[280003042] = {
		['ID'] = 280003042,
		['ShopType'] = 3,
		['ShopType1'] = 4,
		['TabName'] = 'VIP商店',
		['GroupingName'] = 'VIP2商店',
		['OpenConditionType'] = 2,
		['OpenCondition'] = 'VIP等级达到2级',
		['StartTime'] = 0,
		['EndTime'] = 0,
		['ConsumptionType'] = 2,
		['TabDescribe'] = ''
		},
	[280003043] = {
		['ID'] = 280003043,
		['ShopType'] = 3,
		['ShopType1'] = 4,
		['TabName'] = 'VIP商店',
		['GroupingName'] = 'VIP3商店',
		['OpenConditionType'] = 3,
		['OpenCondition'] = 'VIP等级达到3级',
		['StartTime'] = 0,
		['EndTime'] = 0,
		['ConsumptionType'] = 2,
		['TabDescribe'] = ''
		}
	}
return ShopListTable
