local ShopListTable = {
	[280001011] = {
		['ID'] = 280001011,	--索引
		['ShopType'] = 1,	--商城类型
		['ShopType1'] = 1,	--商城小类型
		['TabName'] = '铁匠铺',	--页签名称
		['GroupingName'] = '铁匠铺',	--分组名称
		['OpenConditionType'] = 0,	--开放条件类型
		['OpenCondition'] = '',	--开放条件
		['StartTime'] = 0,	--开始时间
		['EndTime'] = 0,	--结束时间
		['ConsumptionType'] = 3,	--货币类型
		['TabDescribe'] = ''	--页签说明
		},
	[280001012] = {
		['ID'] = 280001012,
		['ShopType'] = 1,
		['ShopType1'] = 2,
		['TabName'] = '奇珍阁',
		['GroupingName'] = '奇珍阁',
		['OpenConditionType'] = 0,
		['OpenCondition'] = '',
		['StartTime'] = 0,
		['EndTime'] = 0,
		['ConsumptionType'] = 3,
		['TabDescribe'] = ''
		},
	[280001013] = {
		['ID'] = 280001013,
		['ShopType'] = 1,
		['ShopType1'] = 3,
		['TabName'] = '杂货铺',
		['GroupingName'] = '杂货铺',
		['OpenConditionType'] = 0,
		['OpenCondition'] = '',
		['StartTime'] = 0,
		['EndTime'] = 0,
		['ConsumptionType'] = 3,
		['TabDescribe'] = ''
		},
	[280001014] = {
		['ID'] = 280001014,
		['ShopType'] = 1,
		['ShopType1'] = 5,
		['TabName'] = '八卦',
		['GroupingName'] = '八卦',
		['OpenConditionType'] = 0,
		['OpenCondition'] = '',
		['StartTime'] = 0,
		['EndTime'] = 0,
		['ConsumptionType'] = 3,
		['TabDescribe'] = ''
		},
	[280003011] = {
		['ID'] = 280003011,
		['ShopType'] = 3,
		['ShopType1'] = 2,
		['TabName'] = '军需商店',
		['GroupingName'] = '军需商店',
		['OpenConditionType'] = 0,
		['OpenCondition'] = '',
		['StartTime'] = 0,
		['EndTime'] = 0,
		['ConsumptionType'] = 6,
		['TabDescribe'] = '使用功勋可兑换下列物品'
		},
	[280003012] = {
		['ID'] = 280003012,
		['ShopType'] = 3,
		['ShopType1'] = 1,
		['TabName'] = '修炼商店',
		['GroupingName'] = '修炼商店',
		['OpenConditionType'] = 0,
		['OpenCondition'] = '',
		['StartTime'] = 0,
		['EndTime'] = 0,
		['ConsumptionType'] = 5,
		['TabDescribe'] = '使用门宗贡献可兑换下列物品'
		},
	[280003013] = {
		['ID'] = 280003013,
		['ShopType'] = 3,
		['ShopType1'] = 5,
		['TabName'] = '灵宝商店',
		['GroupingName'] = '灵宝商店',
		['OpenConditionType'] = 16,
		['OpenCondition'] = '玩家等级达到16级',
		['StartTime'] = 0,
		['EndTime'] = 0,
		['ConsumptionType'] = 8,
		['TabDescribe'] = '使用灵石可兑换下列物品'
		},
	[280003014] = {
		['ID'] = 280003014,
		['ShopType'] = 3,
		['ShopType1'] = 4,
		['TabName'] = '伙伴商店',
		['GroupingName'] = '伙伴商店',
		['OpenConditionType'] = 0,
		['OpenCondition'] = '',
		['StartTime'] = 0,
		['EndTime'] = 0,
		['ConsumptionType'] = 10,
		['TabDescribe'] = '使用血晶可兑换下列物品'
		},
	[280003021] = {
		['ID'] = 280003021,
		['ShopType'] = 3,
		['ShopType1'] = 3,
		['TabName'] = '名望商店',
		['GroupingName'] = '名望商店',
		['OpenConditionType'] = 0,
		['OpenCondition'] = '',
		['StartTime'] = 0,
		['EndTime'] = 0,
		['ConsumptionType'] = 9,
		['TabDescribe'] = '使用声望可兑换下列物品'
		}
	}
return ShopListTable
