/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "comm_message.pb-c.h"
void   comm_answer__init
                     (CommAnswer         *message)
{
  static CommAnswer init_value = COMM_ANSWER__INIT;
  *message = init_value;
}
size_t comm_answer__get_packed_size
                     (const CommAnswer *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &comm_answer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t comm_answer__pack
                     (const CommAnswer *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &comm_answer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t comm_answer__pack_to_buffer
                     (const CommAnswer *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &comm_answer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CommAnswer *
       comm_answer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CommAnswer *)
     protobuf_c_message_unpack (&comm_answer__descriptor,
                                allocator, len, data);
}
void   comm_answer__free_unpacked
                     (CommAnswer *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &comm_answer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pos_data__init
                     (PosData         *message)
{
  static PosData init_value = POS_DATA__INIT;
  *message = init_value;
}
size_t pos_data__get_packed_size
                     (const PosData *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &pos_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pos_data__pack
                     (const PosData *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &pos_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pos_data__pack_to_buffer
                     (const PosData *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &pos_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PosData *
       pos_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PosData *)
     protobuf_c_message_unpack (&pos_data__descriptor,
                                allocator, len, data);
}
void   pos_data__free_unpacked
                     (PosData *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &pos_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   buff_info__init
                     (BuffInfo         *message)
{
  static BuffInfo init_value = BUFF_INFO__INIT;
  *message = init_value;
}
size_t buff_info__get_packed_size
                     (const BuffInfo *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &buff_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t buff_info__pack
                     (const BuffInfo *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &buff_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t buff_info__pack_to_buffer
                     (const BuffInfo *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &buff_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BuffInfo *
       buff_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BuffInfo *)
     protobuf_c_message_unpack (&buff_info__descriptor,
                                allocator, len, data);
}
void   buff_info__free_unpacked
                     (BuffInfo *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &buff_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   attr_data__init
                     (AttrData         *message)
{
  static AttrData init_value = ATTR_DATA__INIT;
  *message = init_value;
}
size_t attr_data__get_packed_size
                     (const AttrData *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &attr_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t attr_data__pack
                     (const AttrData *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &attr_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t attr_data__pack_to_buffer
                     (const AttrData *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &attr_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AttrData *
       attr_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AttrData *)
     protobuf_c_message_unpack (&attr_data__descriptor,
                                allocator, len, data);
}
void   attr_data__free_unpacked
                     (AttrData *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &attr_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   player_base_info__init
                     (PlayerBaseInfo         *message)
{
  static PlayerBaseInfo init_value = PLAYER_BASE_INFO__INIT;
  *message = init_value;
}
size_t player_base_info__get_packed_size
                     (const PlayerBaseInfo *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &player_base_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t player_base_info__pack
                     (const PlayerBaseInfo *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &player_base_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t player_base_info__pack_to_buffer
                     (const PlayerBaseInfo *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &player_base_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PlayerBaseInfo *
       player_base_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PlayerBaseInfo *)
     protobuf_c_message_unpack (&player_base_info__descriptor,
                                allocator, len, data);
}
void   player_base_info__free_unpacked
                     (PlayerBaseInfo *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &player_base_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   item_bagua_data__init
                     (ItemBaguaData         *message)
{
  static ItemBaguaData init_value = ITEM_BAGUA_DATA__INIT;
  *message = init_value;
}
size_t item_bagua_data__get_packed_size
                     (const ItemBaguaData *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &item_bagua_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t item_bagua_data__pack
                     (const ItemBaguaData *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &item_bagua_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t item_bagua_data__pack_to_buffer
                     (const ItemBaguaData *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &item_bagua_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ItemBaguaData *
       item_bagua_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ItemBaguaData *)
     protobuf_c_message_unpack (&item_bagua_data__descriptor,
                                allocator, len, data);
}
void   item_bagua_data__free_unpacked
                     (ItemBaguaData *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &item_bagua_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bag_grid__init
                     (BagGrid         *message)
{
  static BagGrid init_value = BAG_GRID__INIT;
  *message = init_value;
}
size_t bag_grid__get_packed_size
                     (const BagGrid *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &bag_grid__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bag_grid__pack
                     (const BagGrid *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &bag_grid__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bag_grid__pack_to_buffer
                     (const BagGrid *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &bag_grid__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BagGrid *
       bag_grid__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BagGrid *)
     protobuf_c_message_unpack (&bag_grid__descriptor,
                                allocator, len, data);
}
void   bag_grid__free_unpacked
                     (BagGrid *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &bag_grid__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   item_data__init
                     (ItemData         *message)
{
  static ItemData init_value = ITEM_DATA__INIT;
  *message = init_value;
}
size_t item_data__get_packed_size
                     (const ItemData *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &item_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t item_data__pack
                     (const ItemData *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &item_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t item_data__pack_to_buffer
                     (const ItemData *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &item_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ItemData *
       item_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ItemData *)
     protobuf_c_message_unpack (&item_data__descriptor,
                                allocator, len, data);
}
void   item_data__free_unpacked
                     (ItemData *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &item_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   head_icon_data__init
                     (HeadIconData         *message)
{
  static HeadIconData init_value = HEAD_ICON_DATA__INIT;
  *message = init_value;
}
size_t head_icon_data__get_packed_size
                     (const HeadIconData *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &head_icon_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t head_icon_data__pack
                     (const HeadIconData *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &head_icon_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t head_icon_data__pack_to_buffer
                     (const HeadIconData *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &head_icon_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
HeadIconData *
       head_icon_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (HeadIconData *)
     protobuf_c_message_unpack (&head_icon_data__descriptor,
                                allocator, len, data);
}
void   head_icon_data__free_unpacked
                     (HeadIconData *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &head_icon_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   task_count__init
                     (TaskCount         *message)
{
  static TaskCount init_value = TASK_COUNT__INIT;
  *message = init_value;
}
size_t task_count__get_packed_size
                     (const TaskCount *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &task_count__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t task_count__pack
                     (const TaskCount *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &task_count__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t task_count__pack_to_buffer
                     (const TaskCount *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &task_count__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TaskCount *
       task_count__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TaskCount *)
     protobuf_c_message_unpack (&task_count__descriptor,
                                allocator, len, data);
}
void   task_count__free_unpacked
                     (TaskCount *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &task_count__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   task_reward_data__init
                     (TaskRewardData         *message)
{
  static TaskRewardData init_value = TASK_REWARD_DATA__INIT;
  *message = init_value;
}
size_t task_reward_data__get_packed_size
                     (const TaskRewardData *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &task_reward_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t task_reward_data__pack
                     (const TaskRewardData *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &task_reward_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t task_reward_data__pack_to_buffer
                     (const TaskRewardData *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &task_reward_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TaskRewardData *
       task_reward_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TaskRewardData *)
     protobuf_c_message_unpack (&task_reward_data__descriptor,
                                allocator, len, data);
}
void   task_reward_data__free_unpacked
                     (TaskRewardData *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &task_reward_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   task_data__init
                     (TaskData         *message)
{
  static TaskData init_value = TASK_DATA__INIT;
  *message = init_value;
}
size_t task_data__get_packed_size
                     (const TaskData *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &task_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t task_data__pack
                     (const TaskData *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &task_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t task_data__pack_to_buffer
                     (const TaskData *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &task_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TaskData *
       task_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TaskData *)
     protobuf_c_message_unpack (&task_data__descriptor,
                                allocator, len, data);
}
void   task_data__free_unpacked
                     (TaskData *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &task_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   player_online_state__init
                     (PlayerOnlineState         *message)
{
  static PlayerOnlineState init_value = PLAYER_ONLINE_STATE__INIT;
  *message = init_value;
}
size_t player_online_state__get_packed_size
                     (const PlayerOnlineState *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &player_online_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t player_online_state__pack
                     (const PlayerOnlineState *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &player_online_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t player_online_state__pack_to_buffer
                     (const PlayerOnlineState *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &player_online_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PlayerOnlineState *
       player_online_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PlayerOnlineState *)
     protobuf_c_message_unpack (&player_online_state__descriptor,
                                allocator, len, data);
}
void   player_online_state__free_unpacked
                     (PlayerOnlineState *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &player_online_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   equip_enchant_data__init
                     (EquipEnchantData         *message)
{
  static EquipEnchantData init_value = EQUIP_ENCHANT_DATA__INIT;
  *message = init_value;
}
size_t equip_enchant_data__get_packed_size
                     (const EquipEnchantData *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &equip_enchant_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t equip_enchant_data__pack
                     (const EquipEnchantData *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &equip_enchant_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t equip_enchant_data__pack_to_buffer
                     (const EquipEnchantData *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &equip_enchant_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EquipEnchantData *
       equip_enchant_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EquipEnchantData *)
     protobuf_c_message_unpack (&equip_enchant_data__descriptor,
                                allocator, len, data);
}
void   equip_enchant_data__free_unpacked
                     (EquipEnchantData *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &equip_enchant_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   equip_data__init
                     (EquipData         *message)
{
  static EquipData init_value = EQUIP_DATA__INIT;
  *message = init_value;
}
size_t equip_data__get_packed_size
                     (const EquipData *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &equip_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t equip_data__pack
                     (const EquipData *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &equip_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t equip_data__pack_to_buffer
                     (const EquipData *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &equip_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EquipData *
       equip_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EquipData *)
     protobuf_c_message_unpack (&equip_data__descriptor,
                                allocator, len, data);
}
void   equip_data__free_unpacked
                     (EquipData *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &equip_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mail_data__init
                     (MailData         *message)
{
  static MailData init_value = MAIL_DATA__INIT;
  *message = init_value;
}
size_t mail_data__get_packed_size
                     (const MailData *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mail_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mail_data__pack
                     (const MailData *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mail_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mail_data__pack_to_buffer
                     (const MailData *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mail_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MailData *
       mail_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MailData *)
     protobuf_c_message_unpack (&mail_data__descriptor,
                                allocator, len, data);
}
void   mail_data__free_unpacked
                     (MailData *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mail_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   goods_data__init
                     (GoodsData         *message)
{
  static GoodsData init_value = GOODS_DATA__INIT;
  *message = init_value;
}
size_t goods_data__get_packed_size
                     (const GoodsData *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &goods_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t goods_data__pack
                     (const GoodsData *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &goods_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t goods_data__pack_to_buffer
                     (const GoodsData *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &goods_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GoodsData *
       goods_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GoodsData *)
     protobuf_c_message_unpack (&goods_data__descriptor,
                                allocator, len, data);
}
void   goods_data__free_unpacked
                     (GoodsData *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &goods_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   player_base_data__init
                     (PlayerBaseData         *message)
{
  static PlayerBaseData init_value = PLAYER_BASE_DATA__INIT;
  *message = init_value;
}
size_t player_base_data__get_packed_size
                     (const PlayerBaseData *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &player_base_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t player_base_data__pack
                     (const PlayerBaseData *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &player_base_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t player_base_data__pack_to_buffer
                     (const PlayerBaseData *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &player_base_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PlayerBaseData *
       player_base_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PlayerBaseData *)
     protobuf_c_message_unpack (&player_base_data__descriptor,
                                allocator, len, data);
}
void   player_base_data__free_unpacked
                     (PlayerBaseData *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &player_base_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor comm_answer__field_descriptors[1] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CommAnswer, result),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned comm_answer__field_indices_by_name[] = {
  0,   /* field[0] = result */
};
static const ProtobufCIntRange comm_answer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor comm_answer__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "comm_answer",
  "CommAnswer",
  "CommAnswer",
  "",
  sizeof(CommAnswer),
  1,
  comm_answer__field_descriptors,
  comm_answer__field_indices_by_name,
  1,  comm_answer__number_ranges,
  (ProtobufCMessageInit) comm_answer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pos_data__field_descriptors[2] =
{
  {
    "pos_x",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PosData, pos_x),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_z",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PosData, pos_z),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pos_data__field_indices_by_name[] = {
  0,   /* field[0] = pos_x */
  1,   /* field[1] = pos_z */
};
static const ProtobufCIntRange pos_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pos_data__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "pos_data",
  "PosData",
  "PosData",
  "",
  sizeof(PosData),
  2,
  pos_data__field_descriptors,
  pos_data__field_indices_by_name,
  1,  pos_data__number_ranges,
  (ProtobufCMessageInit) pos_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor buff_info__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(BuffInfo, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_time",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(BuffInfo, start_time),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned buff_info__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = start_time */
};
static const ProtobufCIntRange buff_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor buff_info__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "buff_info",
  "BuffInfo",
  "BuffInfo",
  "",
  sizeof(BuffInfo),
  2,
  buff_info__field_descriptors,
  buff_info__field_indices_by_name,
  1,  buff_info__number_ranges,
  (ProtobufCMessageInit) buff_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor attr_data__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(AttrData, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "val",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(AttrData, val),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned attr_data__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = val */
};
static const ProtobufCIntRange attr_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor attr_data__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "AttrData",
  "AttrData",
  "AttrData",
  "",
  sizeof(AttrData),
  2,
  attr_data__field_descriptors,
  attr_data__field_indices_by_name,
  1,  attr_data__number_ranges,
  (ProtobufCMessageInit) attr_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor player_base_info__field_descriptors[4] =
{
  {
    "playerId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PlayerBaseInfo, playerid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PlayerBaseInfo, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attrId",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(PlayerBaseInfo, n_attrid),
    PROTOBUF_C_OFFSETOF(PlayerBaseInfo, attrid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attrVal",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(PlayerBaseInfo, n_attrval),
    PROTOBUF_C_OFFSETOF(PlayerBaseInfo, attrval),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned player_base_info__field_indices_by_name[] = {
  2,   /* field[2] = attrId */
  3,   /* field[3] = attrVal */
  1,   /* field[1] = name */
  0,   /* field[0] = playerId */
};
static const ProtobufCIntRange player_base_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor player_base_info__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PlayerBaseInfo",
  "PlayerBaseInfo",
  "PlayerBaseInfo",
  "",
  sizeof(PlayerBaseInfo),
  4,
  player_base_info__field_descriptors,
  player_base_info__field_indices_by_name,
  1,  player_base_info__number_ranges,
  (ProtobufCMessageInit) player_base_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor item_bagua_data__field_descriptors[3] =
{
  {
    "star",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ItemBaguaData, star),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "main_attr_val",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ItemBaguaData, main_attr_val),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "minor_attrs",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(ItemBaguaData, n_minor_attrs),
    PROTOBUF_C_OFFSETOF(ItemBaguaData, minor_attrs),
    &attr_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned item_bagua_data__field_indices_by_name[] = {
  1,   /* field[1] = main_attr_val */
  2,   /* field[2] = minor_attrs */
  0,   /* field[0] = star */
};
static const ProtobufCIntRange item_bagua_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor item_bagua_data__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ItemBaguaData",
  "ItemBaguaData",
  "ItemBaguaData",
  "",
  sizeof(ItemBaguaData),
  3,
  item_bagua_data__field_descriptors,
  item_bagua_data__field_indices_by_name,
  1,  item_bagua_data__number_ranges,
  (ProtobufCMessageInit) item_bagua_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor bag_grid__field_descriptors[6] =
{
  {
    "index",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(BagGrid, index),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(BagGrid, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(BagGrid, num),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "usedCount",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(BagGrid, usedcount),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expireTime",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(BagGrid, expiretime),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bagua",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(BagGrid, bagua),
    &item_bagua_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bag_grid__field_indices_by_name[] = {
  5,   /* field[5] = bagua */
  4,   /* field[4] = expireTime */
  1,   /* field[1] = id */
  0,   /* field[0] = index */
  2,   /* field[2] = num */
  3,   /* field[3] = usedCount */
};
static const ProtobufCIntRange bag_grid__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor bag_grid__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "BagGrid",
  "BagGrid",
  "BagGrid",
  "",
  sizeof(BagGrid),
  6,
  bag_grid__field_descriptors,
  bag_grid__field_indices_by_name,
  1,  bag_grid__number_ranges,
  (ProtobufCMessageInit) bag_grid__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor item_data__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ItemData, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ItemData, num),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned item_data__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = num */
};
static const ProtobufCIntRange item_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor item_data__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ItemData",
  "ItemData",
  "ItemData",
  "",
  sizeof(ItemData),
  2,
  item_data__field_descriptors,
  item_data__field_indices_by_name,
  1,  item_data__number_ranges,
  (ProtobufCMessageInit) item_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor head_icon_data__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(HeadIconData, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(HeadIconData, status),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned head_icon_data__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange head_icon_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor head_icon_data__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "HeadIconData",
  "HeadIconData",
  "HeadIconData",
  "",
  sizeof(HeadIconData),
  2,
  head_icon_data__field_descriptors,
  head_icon_data__field_indices_by_name,
  1,  head_icon_data__number_ranges,
  (ProtobufCMessageInit) head_icon_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor task_count__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TaskCount, type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TaskCount, count),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned task_count__field_indices_by_name[] = {
  1,   /* field[1] = count */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange task_count__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor task_count__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "TaskCount",
  "TaskCount",
  "TaskCount",
  "",
  sizeof(TaskCount),
  2,
  task_count__field_descriptors,
  task_count__field_indices_by_name,
  1,  task_count__number_ranges,
  (ProtobufCMessageInit) task_count__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor task_reward_data__field_descriptors[1] =
{
  {
    "items",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(TaskRewardData, n_items),
    PROTOBUF_C_OFFSETOF(TaskRewardData, items),
    &item_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned task_reward_data__field_indices_by_name[] = {
  0,   /* field[0] = items */
};
static const ProtobufCIntRange task_reward_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor task_reward_data__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "TaskRewardData",
  "TaskRewardData",
  "TaskRewardData",
  "",
  sizeof(TaskRewardData),
  1,
  task_reward_data__field_descriptors,
  task_reward_data__field_indices_by_name,
  1,  task_reward_data__number_ranges,
  (ProtobufCMessageInit) task_reward_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor task_data__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TaskData, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TaskData, status),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expireTime",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TaskData, expiretime),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "progress",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(TaskData, n_progress),
    PROTOBUF_C_OFFSETOF(TaskData, progress),
    &task_count__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reward",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TaskData, reward),
    &task_reward_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned task_data__field_indices_by_name[] = {
  2,   /* field[2] = expireTime */
  0,   /* field[0] = id */
  3,   /* field[3] = progress */
  4,   /* field[4] = reward */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange task_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor task_data__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "TaskData",
  "TaskData",
  "TaskData",
  "",
  sizeof(TaskData),
  5,
  task_data__field_descriptors,
  task_data__field_indices_by_name,
  1,  task_data__number_ranges,
  (ProtobufCMessageInit) task_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor player_online_state__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PlayerOnlineState, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PlayerOnlineState, state),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned player_online_state__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = state */
};
static const ProtobufCIntRange player_online_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor player_online_state__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PlayerOnlineState",
  "PlayerOnlineState",
  "PlayerOnlineState",
  "",
  sizeof(PlayerOnlineState),
  2,
  player_online_state__field_descriptors,
  player_online_state__field_indices_by_name,
  1,  player_online_state__number_ranges,
  (ProtobufCMessageInit) player_online_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor equip_enchant_data__field_descriptors[3] =
{
  {
    "index",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(EquipEnchantData, index),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "curAttr",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(EquipEnchantData, curattr),
    &attr_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "randAttr",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(EquipEnchantData, n_randattr),
    PROTOBUF_C_OFFSETOF(EquipEnchantData, randattr),
    &attr_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned equip_enchant_data__field_indices_by_name[] = {
  1,   /* field[1] = curAttr */
  0,   /* field[0] = index */
  2,   /* field[2] = randAttr */
};
static const ProtobufCIntRange equip_enchant_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor equip_enchant_data__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "EquipEnchantData",
  "EquipEnchantData",
  "EquipEnchantData",
  "",
  sizeof(EquipEnchantData),
  3,
  equip_enchant_data__field_descriptors,
  equip_enchant_data__field_indices_by_name,
  1,  equip_enchant_data__number_ranges,
  (ProtobufCMessageInit) equip_enchant_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor equip_data__field_descriptors[6] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(EquipData, type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stair",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(EquipData, stair),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "starLv",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(EquipData, starlv),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "starExp",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(EquipData, starexp),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enchant",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(EquipData, n_enchant),
    PROTOBUF_C_OFFSETOF(EquipData, enchant),
    &equip_enchant_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inlay",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(EquipData, n_inlay),
    PROTOBUF_C_OFFSETOF(EquipData, inlay),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned equip_data__field_indices_by_name[] = {
  4,   /* field[4] = enchant */
  5,   /* field[5] = inlay */
  1,   /* field[1] = stair */
  3,   /* field[3] = starExp */
  2,   /* field[2] = starLv */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange equip_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor equip_data__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "EquipData",
  "EquipData",
  "EquipData",
  "",
  sizeof(EquipData),
  6,
  equip_data__field_descriptors,
  equip_data__field_indices_by_name,
  1,  equip_data__number_ranges,
  (ProtobufCMessageInit) equip_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mail_data__field_descriptors[10] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MailData, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MailData, type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "title",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MailData, title),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "senderName",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MailData, sendername),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MailData, content),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "args",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(MailData, n_args),
    PROTOBUF_C_OFFSETOF(MailData, args),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sendTime",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MailData, sendtime),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attach",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(MailData, n_attach),
    PROTOBUF_C_OFFSETOF(MailData, attach),
    &item_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "read",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MailData, read),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "extract",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MailData, extract),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mail_data__field_indices_by_name[] = {
  5,   /* field[5] = args */
  7,   /* field[7] = attach */
  4,   /* field[4] = content */
  9,   /* field[9] = extract */
  0,   /* field[0] = id */
  8,   /* field[8] = read */
  6,   /* field[6] = sendTime */
  3,   /* field[3] = senderName */
  2,   /* field[2] = title */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange mail_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor mail_data__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "MailData",
  "MailData",
  "MailData",
  "",
  sizeof(MailData),
  10,
  mail_data__field_descriptors,
  mail_data__field_indices_by_name,
  1,  mail_data__number_ranges,
  (ProtobufCMessageInit) mail_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor goods_data__field_descriptors[2] =
{
  {
    "goodsId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GoodsData, goodsid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "boughtNum",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GoodsData, boughtnum),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned goods_data__field_indices_by_name[] = {
  1,   /* field[1] = boughtNum */
  0,   /* field[0] = goodsId */
};
static const ProtobufCIntRange goods_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor goods_data__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "GoodsData",
  "GoodsData",
  "GoodsData",
  "",
  sizeof(GoodsData),
  2,
  goods_data__field_descriptors,
  goods_data__field_indices_by_name,
  1,  goods_data__number_ranges,
  (ProtobufCMessageInit) goods_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor player_base_data__field_descriptors[5] =
{
  {
    "playerId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PlayerBaseData, playerid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PlayerBaseData, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attrs",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(PlayerBaseData, n_attrs),
    PROTOBUF_C_OFFSETOF(PlayerBaseData, attrs),
    &attr_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tags",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(PlayerBaseData, n_tags),
    PROTOBUF_C_OFFSETOF(PlayerBaseData, tags),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "textIntro",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PlayerBaseData, textintro),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned player_base_data__field_indices_by_name[] = {
  2,   /* field[2] = attrs */
  1,   /* field[1] = name */
  0,   /* field[0] = playerId */
  3,   /* field[3] = tags */
  4,   /* field[4] = textIntro */
};
static const ProtobufCIntRange player_base_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor player_base_data__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PlayerBaseData",
  "PlayerBaseData",
  "PlayerBaseData",
  "",
  sizeof(PlayerBaseData),
  5,
  player_base_data__field_descriptors,
  player_base_data__field_indices_by_name,
  1,  player_base_data__number_ranges,
  (ProtobufCMessageInit) player_base_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue task_status__enum_values_by_number[7] =
{
  { "NOT_ACCEPT_YET", "TASK_STATUS__NOT_ACCEPT_YET", 0 },
  { "UNACCEPTABLE", "TASK_STATUS__UNACCEPTABLE", 1 },
  { "ACCEPTABLE", "TASK_STATUS__ACCEPTABLE", 2 },
  { "ACCEPTED", "TASK_STATUS__ACCEPTED", 3 },
  { "ACHIEVED", "TASK_STATUS__ACHIEVED", 4 },
  { "FINISH", "TASK_STATUS__FINISH", 5 },
  { "UNACHIEVABLE", "TASK_STATUS__UNACHIEVABLE", 6 },
};
static const ProtobufCIntRange task_status__value_ranges[] = {
{0, 0},{0, 7}
};
const ProtobufCEnumValueIndex task_status__enum_values_by_name[7] =
{
  { "ACCEPTABLE", 2 },
  { "ACCEPTED", 3 },
  { "ACHIEVED", 4 },
  { "FINISH", 5 },
  { "NOT_ACCEPT_YET", 0 },
  { "UNACCEPTABLE", 1 },
  { "UNACHIEVABLE", 6 },
};
const ProtobufCEnumDescriptor task_status__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "TaskStatus",
  "TaskStatus",
  "TaskStatus",
  "",
  7,
  task_status__enum_values_by_number,
  7,
  task_status__enum_values_by_name,
  1,
  task_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
