/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "mail.pb-c.h"
void   mail_comm_request__init
                     (MailCommRequest         *message)
{
  static MailCommRequest init_value = MAIL_COMM_REQUEST__INIT;
  *message = init_value;
}
size_t mail_comm_request__get_packed_size
                     (const MailCommRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mail_comm_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mail_comm_request__pack
                     (const MailCommRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mail_comm_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mail_comm_request__pack_to_buffer
                     (const MailCommRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mail_comm_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MailCommRequest *
       mail_comm_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MailCommRequest *)
     protobuf_c_message_unpack (&mail_comm_request__descriptor,
                                allocator, len, data);
}
void   mail_comm_request__free_unpacked
                     (MailCommRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mail_comm_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mail_comm_answer__init
                     (MailCommAnswer         *message)
{
  static MailCommAnswer init_value = MAIL_COMM_ANSWER__INIT;
  *message = init_value;
}
size_t mail_comm_answer__get_packed_size
                     (const MailCommAnswer *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mail_comm_answer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mail_comm_answer__pack
                     (const MailCommAnswer *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mail_comm_answer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mail_comm_answer__pack_to_buffer
                     (const MailCommAnswer *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mail_comm_answer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MailCommAnswer *
       mail_comm_answer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MailCommAnswer *)
     protobuf_c_message_unpack (&mail_comm_answer__descriptor,
                                allocator, len, data);
}
void   mail_comm_answer__free_unpacked
                     (MailCommAnswer *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mail_comm_answer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mail_list_answer__init
                     (MailListAnswer         *message)
{
  static MailListAnswer init_value = MAIL_LIST_ANSWER__INIT;
  *message = init_value;
}
size_t mail_list_answer__get_packed_size
                     (const MailListAnswer *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mail_list_answer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mail_list_answer__pack
                     (const MailListAnswer *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mail_list_answer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mail_list_answer__pack_to_buffer
                     (const MailListAnswer *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mail_list_answer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MailListAnswer *
       mail_list_answer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MailListAnswer *)
     protobuf_c_message_unpack (&mail_list_answer__descriptor,
                                allocator, len, data);
}
void   mail_list_answer__free_unpacked
                     (MailListAnswer *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mail_list_answer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mail_multi_answer__init
                     (MailMultiAnswer         *message)
{
  static MailMultiAnswer init_value = MAIL_MULTI_ANSWER__INIT;
  *message = init_value;
}
size_t mail_multi_answer__get_packed_size
                     (const MailMultiAnswer *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mail_multi_answer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mail_multi_answer__pack
                     (const MailMultiAnswer *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mail_multi_answer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mail_multi_answer__pack_to_buffer
                     (const MailMultiAnswer *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mail_multi_answer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MailMultiAnswer *
       mail_multi_answer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MailMultiAnswer *)
     protobuf_c_message_unpack (&mail_multi_answer__descriptor,
                                allocator, len, data);
}
void   mail_multi_answer__free_unpacked
                     (MailMultiAnswer *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mail_multi_answer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor mail_comm_request__field_descriptors[1] =
{
  {
    "mail_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MailCommRequest, mail_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mail_comm_request__field_indices_by_name[] = {
  0,   /* field[0] = mail_id */
};
static const ProtobufCIntRange mail_comm_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mail_comm_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "MailCommRequest",
  "MailCommRequest",
  "MailCommRequest",
  "",
  sizeof(MailCommRequest),
  1,
  mail_comm_request__field_descriptors,
  mail_comm_request__field_indices_by_name,
  1,  mail_comm_request__number_ranges,
  (ProtobufCMessageInit) mail_comm_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mail_comm_answer__field_descriptors[2] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MailCommAnswer, result),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mail_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MailCommAnswer, mail_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mail_comm_answer__field_indices_by_name[] = {
  1,   /* field[1] = mail_id */
  0,   /* field[0] = result */
};
static const ProtobufCIntRange mail_comm_answer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mail_comm_answer__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "MailCommAnswer",
  "MailCommAnswer",
  "MailCommAnswer",
  "",
  sizeof(MailCommAnswer),
  2,
  mail_comm_answer__field_descriptors,
  mail_comm_answer__field_indices_by_name,
  1,  mail_comm_answer__number_ranges,
  (ProtobufCMessageInit) mail_comm_answer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mail_list_answer__field_descriptors[2] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MailListAnswer, result),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mails",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(MailListAnswer, n_mails),
    PROTOBUF_C_OFFSETOF(MailListAnswer, mails),
    &mail_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mail_list_answer__field_indices_by_name[] = {
  1,   /* field[1] = mails */
  0,   /* field[0] = result */
};
static const ProtobufCIntRange mail_list_answer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mail_list_answer__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "MailListAnswer",
  "MailListAnswer",
  "MailListAnswer",
  "",
  sizeof(MailListAnswer),
  2,
  mail_list_answer__field_descriptors,
  mail_list_answer__field_indices_by_name,
  1,  mail_list_answer__number_ranges,
  (ProtobufCMessageInit) mail_list_answer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mail_multi_answer__field_descriptors[2] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MailMultiAnswer, result),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mail_id",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(MailMultiAnswer, n_mail_id),
    PROTOBUF_C_OFFSETOF(MailMultiAnswer, mail_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mail_multi_answer__field_indices_by_name[] = {
  1,   /* field[1] = mail_id */
  0,   /* field[0] = result */
};
static const ProtobufCIntRange mail_multi_answer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mail_multi_answer__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "MailMultiAnswer",
  "MailMultiAnswer",
  "MailMultiAnswer",
  "",
  sizeof(MailMultiAnswer),
  2,
  mail_multi_answer__field_descriptors,
  mail_multi_answer__field_indices_by_name,
  1,  mail_multi_answer__number_ranges,
  (ProtobufCMessageInit) mail_multi_answer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
