/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "move.pb-c.h"
void   move_request__init
                     (MoveRequest         *message)
{
  static MoveRequest init_value = MOVE_REQUEST__INIT;
  *message = init_value;
}
size_t move_request__get_packed_size
                     (const MoveRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &move_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t move_request__pack
                     (const MoveRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &move_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t move_request__pack_to_buffer
                     (const MoveRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &move_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MoveRequest *
       move_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MoveRequest *)
     protobuf_c_message_unpack (&move_request__descriptor,
                                allocator, len, data);
}
void   move_request__free_unpacked
                     (MoveRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &move_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   move_notify__init
                     (MoveNotify         *message)
{
  static MoveNotify init_value = MOVE_NOTIFY__INIT;
  *message = init_value;
}
size_t move_notify__get_packed_size
                     (const MoveNotify *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &move_notify__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t move_notify__pack
                     (const MoveNotify *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &move_notify__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t move_notify__pack_to_buffer
                     (const MoveNotify *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &move_notify__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MoveNotify *
       move_notify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MoveNotify *)
     protobuf_c_message_unpack (&move_notify__descriptor,
                                allocator, len, data);
}
void   move_notify__free_unpacked
                     (MoveNotify *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &move_notify__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sync_player_pos_notify__init
                     (SyncPlayerPosNotify         *message)
{
  static SyncPlayerPosNotify init_value = SYNC_PLAYER_POS_NOTIFY__INIT;
  *message = init_value;
}
size_t sync_player_pos_notify__get_packed_size
                     (const SyncPlayerPosNotify *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sync_player_pos_notify__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sync_player_pos_notify__pack
                     (const SyncPlayerPosNotify *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sync_player_pos_notify__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sync_player_pos_notify__pack_to_buffer
                     (const SyncPlayerPosNotify *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sync_player_pos_notify__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SyncPlayerPosNotify *
       sync_player_pos_notify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SyncPlayerPosNotify *)
     protobuf_c_message_unpack (&sync_player_pos_notify__descriptor,
                                allocator, len, data);
}
void   sync_player_pos_notify__free_unpacked
                     (SyncPlayerPosNotify *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sync_player_pos_notify__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sight_player_base_info__init
                     (SightPlayerBaseInfo         *message)
{
  static SightPlayerBaseInfo init_value = SIGHT_PLAYER_BASE_INFO__INIT;
  *message = init_value;
}
size_t sight_player_base_info__get_packed_size
                     (const SightPlayerBaseInfo *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_player_base_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sight_player_base_info__pack
                     (const SightPlayerBaseInfo *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_player_base_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sight_player_base_info__pack_to_buffer
                     (const SightPlayerBaseInfo *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_player_base_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SightPlayerBaseInfo *
       sight_player_base_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SightPlayerBaseInfo *)
     protobuf_c_message_unpack (&sight_player_base_info__descriptor,
                                allocator, len, data);
}
void   sight_player_base_info__free_unpacked
                     (SightPlayerBaseInfo *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_player_base_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sight_monster_info__init
                     (SightMonsterInfo         *message)
{
  static SightMonsterInfo init_value = SIGHT_MONSTER_INFO__INIT;
  *message = init_value;
}
size_t sight_monster_info__get_packed_size
                     (const SightMonsterInfo *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_monster_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sight_monster_info__pack
                     (const SightMonsterInfo *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_monster_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sight_monster_info__pack_to_buffer
                     (const SightMonsterInfo *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_monster_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SightMonsterInfo *
       sight_monster_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SightMonsterInfo *)
     protobuf_c_message_unpack (&sight_monster_info__descriptor,
                                allocator, len, data);
}
void   sight_monster_info__free_unpacked
                     (SightMonsterInfo *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_monster_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   player_on_cash_truck_info__init
                     (PlayerOnCashTruckInfo         *message)
{
  static PlayerOnCashTruckInfo init_value = PLAYER_ON_CASH_TRUCK_INFO__INIT;
  *message = init_value;
}
size_t player_on_cash_truck_info__get_packed_size
                     (const PlayerOnCashTruckInfo *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &player_on_cash_truck_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t player_on_cash_truck_info__pack
                     (const PlayerOnCashTruckInfo *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &player_on_cash_truck_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t player_on_cash_truck_info__pack_to_buffer
                     (const PlayerOnCashTruckInfo *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &player_on_cash_truck_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PlayerOnCashTruckInfo *
       player_on_cash_truck_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PlayerOnCashTruckInfo *)
     protobuf_c_message_unpack (&player_on_cash_truck_info__descriptor,
                                allocator, len, data);
}
void   player_on_cash_truck_info__free_unpacked
                     (PlayerOnCashTruckInfo *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &player_on_cash_truck_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sight_cash_truck_info__init
                     (SightCashTruckInfo         *message)
{
  static SightCashTruckInfo init_value = SIGHT_CASH_TRUCK_INFO__INIT;
  *message = init_value;
}
size_t sight_cash_truck_info__get_packed_size
                     (const SightCashTruckInfo *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_cash_truck_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sight_cash_truck_info__pack
                     (const SightCashTruckInfo *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_cash_truck_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sight_cash_truck_info__pack_to_buffer
                     (const SightCashTruckInfo *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_cash_truck_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SightCashTruckInfo *
       sight_cash_truck_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SightCashTruckInfo *)
     protobuf_c_message_unpack (&sight_cash_truck_info__descriptor,
                                allocator, len, data);
}
void   sight_cash_truck_info__free_unpacked
                     (SightCashTruckInfo *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_cash_truck_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sight_collect_info__init
                     (SightCollectInfo         *message)
{
  static SightCollectInfo init_value = SIGHT_COLLECT_INFO__INIT;
  *message = init_value;
}
size_t sight_collect_info__get_packed_size
                     (const SightCollectInfo *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_collect_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sight_collect_info__pack
                     (const SightCollectInfo *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_collect_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sight_collect_info__pack_to_buffer
                     (const SightCollectInfo *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_collect_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SightCollectInfo *
       sight_collect_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SightCollectInfo *)
     protobuf_c_message_unpack (&sight_collect_info__descriptor,
                                allocator, len, data);
}
void   sight_collect_info__free_unpacked
                     (SightCollectInfo *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_collect_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sight_npc_info__init
                     (SightNpcInfo         *message)
{
  static SightNpcInfo init_value = SIGHT_NPC_INFO__INIT;
  *message = init_value;
}
size_t sight_npc_info__get_packed_size
                     (const SightNpcInfo *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_npc_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sight_npc_info__pack
                     (const SightNpcInfo *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_npc_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sight_npc_info__pack_to_buffer
                     (const SightNpcInfo *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_npc_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SightNpcInfo *
       sight_npc_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SightNpcInfo *)
     protobuf_c_message_unpack (&sight_npc_info__descriptor,
                                allocator, len, data);
}
void   sight_npc_info__free_unpacked
                     (SightNpcInfo *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_npc_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sight_trap_info__init
                     (SightTrapInfo         *message)
{
  static SightTrapInfo init_value = SIGHT_TRAP_INFO__INIT;
  *message = init_value;
}
size_t sight_trap_info__get_packed_size
                     (const SightTrapInfo *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_trap_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sight_trap_info__pack
                     (const SightTrapInfo *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_trap_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sight_trap_info__pack_to_buffer
                     (const SightTrapInfo *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_trap_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SightTrapInfo *
       sight_trap_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SightTrapInfo *)
     protobuf_c_message_unpack (&sight_trap_info__descriptor,
                                allocator, len, data);
}
void   sight_trap_info__free_unpacked
                     (SightTrapInfo *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_trap_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sight_partner_info__init
                     (SightPartnerInfo         *message)
{
  static SightPartnerInfo init_value = SIGHT_PARTNER_INFO__INIT;
  *message = init_value;
}
size_t sight_partner_info__get_packed_size
                     (const SightPartnerInfo *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_partner_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sight_partner_info__pack
                     (const SightPartnerInfo *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_partner_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sight_partner_info__pack_to_buffer
                     (const SightPartnerInfo *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_partner_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SightPartnerInfo *
       sight_partner_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SightPartnerInfo *)
     protobuf_c_message_unpack (&sight_partner_info__descriptor,
                                allocator, len, data);
}
void   sight_partner_info__free_unpacked
                     (SightPartnerInfo *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_partner_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sight_changed_notify__init
                     (SightChangedNotify         *message)
{
  static SightChangedNotify init_value = SIGHT_CHANGED_NOTIFY__INIT;
  *message = init_value;
}
size_t sight_changed_notify__get_packed_size
                     (const SightChangedNotify *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_changed_notify__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sight_changed_notify__pack
                     (const SightChangedNotify *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_changed_notify__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sight_changed_notify__pack_to_buffer
                     (const SightChangedNotify *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_changed_notify__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SightChangedNotify *
       sight_changed_notify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SightChangedNotify *)
     protobuf_c_message_unpack (&sight_changed_notify__descriptor,
                                allocator, len, data);
}
void   sight_changed_notify__free_unpacked
                     (SightChangedNotify *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_changed_notify__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   special_monster_pos_notify__init
                     (SpecialMonsterPosNotify         *message)
{
  static SpecialMonsterPosNotify init_value = SPECIAL_MONSTER_POS_NOTIFY__INIT;
  *message = init_value;
}
size_t special_monster_pos_notify__get_packed_size
                     (const SpecialMonsterPosNotify *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &special_monster_pos_notify__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t special_monster_pos_notify__pack
                     (const SpecialMonsterPosNotify *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &special_monster_pos_notify__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t special_monster_pos_notify__pack_to_buffer
                     (const SpecialMonsterPosNotify *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &special_monster_pos_notify__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SpecialMonsterPosNotify *
       special_monster_pos_notify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SpecialMonsterPosNotify *)
     protobuf_c_message_unpack (&special_monster_pos_notify__descriptor,
                                allocator, len, data);
}
void   special_monster_pos_notify__free_unpacked
                     (SpecialMonsterPosNotify *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &special_monster_pos_notify__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   special_player_pos_notify__init
                     (SpecialPlayerPosNotify         *message)
{
  static SpecialPlayerPosNotify init_value = SPECIAL_PLAYER_POS_NOTIFY__INIT;
  *message = init_value;
}
size_t special_player_pos_notify__get_packed_size
                     (const SpecialPlayerPosNotify *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &special_player_pos_notify__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t special_player_pos_notify__pack
                     (const SpecialPlayerPosNotify *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &special_player_pos_notify__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t special_player_pos_notify__pack_to_buffer
                     (const SpecialPlayerPosNotify *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &special_player_pos_notify__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SpecialPlayerPosNotify *
       special_player_pos_notify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SpecialPlayerPosNotify *)
     protobuf_c_message_unpack (&special_player_pos_notify__descriptor,
                                allocator, len, data);
}
void   special_player_pos_notify__free_unpacked
                     (SpecialPlayerPosNotify *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &special_player_pos_notify__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sight_player_info_change_notify__init
                     (SightPlayerInfoChangeNotify         *message)
{
  static SightPlayerInfoChangeNotify init_value = SIGHT_PLAYER_INFO_CHANGE_NOTIFY__INIT;
  *message = init_value;
}
size_t sight_player_info_change_notify__get_packed_size
                     (const SightPlayerInfoChangeNotify *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_player_info_change_notify__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sight_player_info_change_notify__pack
                     (const SightPlayerInfoChangeNotify *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_player_info_change_notify__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sight_player_info_change_notify__pack_to_buffer
                     (const SightPlayerInfoChangeNotify *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_player_info_change_notify__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SightPlayerInfoChangeNotify *
       sight_player_info_change_notify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SightPlayerInfoChangeNotify *)
     protobuf_c_message_unpack (&sight_player_info_change_notify__descriptor,
                                allocator, len, data);
}
void   sight_player_info_change_notify__free_unpacked
                     (SightPlayerInfoChangeNotify *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_player_info_change_notify__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sight_monster_id_change_notify__init
                     (SightMonsterIdChangeNotify         *message)
{
  static SightMonsterIdChangeNotify init_value = SIGHT_MONSTER_ID_CHANGE_NOTIFY__INIT;
  *message = init_value;
}
size_t sight_monster_id_change_notify__get_packed_size
                     (const SightMonsterIdChangeNotify *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_monster_id_change_notify__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sight_monster_id_change_notify__pack
                     (const SightMonsterIdChangeNotify *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_monster_id_change_notify__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sight_monster_id_change_notify__pack_to_buffer
                     (const SightMonsterIdChangeNotify *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_monster_id_change_notify__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SightMonsterIdChangeNotify *
       sight_monster_id_change_notify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SightMonsterIdChangeNotify *)
     protobuf_c_message_unpack (&sight_monster_id_change_notify__descriptor,
                                allocator, len, data);
}
void   sight_monster_id_change_notify__free_unpacked
                     (SightMonsterIdChangeNotify *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sight_monster_id_change_notify__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   monster_talk_notify__init
                     (MonsterTalkNotify         *message)
{
  static MonsterTalkNotify init_value = MONSTER_TALK_NOTIFY__INIT;
  *message = init_value;
}
size_t monster_talk_notify__get_packed_size
                     (const MonsterTalkNotify *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &monster_talk_notify__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t monster_talk_notify__pack
                     (const MonsterTalkNotify *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &monster_talk_notify__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t monster_talk_notify__pack_to_buffer
                     (const MonsterTalkNotify *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &monster_talk_notify__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MonsterTalkNotify *
       monster_talk_notify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MonsterTalkNotify *)
     protobuf_c_message_unpack (&monster_talk_notify__descriptor,
                                allocator, len, data);
}
void   monster_talk_notify__free_unpacked
                     (MonsterTalkNotify *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &monster_talk_notify__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor move_request__field_descriptors[1] =
{
  {
    "data",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(MoveRequest, n_data),
    PROTOBUF_C_OFFSETOF(MoveRequest, data),
    &pos_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned move_request__field_indices_by_name[] = {
  0,   /* field[0] = data */
};
static const ProtobufCIntRange move_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor move_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "move_request",
  "MoveRequest",
  "MoveRequest",
  "",
  sizeof(MoveRequest),
  1,
  move_request__field_descriptors,
  move_request__field_indices_by_name,
  1,  move_request__number_ranges,
  (ProtobufCMessageInit) move_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor move_notify__field_descriptors[2] =
{
  {
    "playerid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MoveNotify, playerid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(MoveNotify, n_data),
    PROTOBUF_C_OFFSETOF(MoveNotify, data),
    &pos_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned move_notify__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = playerid */
};
static const ProtobufCIntRange move_notify__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor move_notify__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "move_notify",
  "MoveNotify",
  "MoveNotify",
  "",
  sizeof(MoveNotify),
  2,
  move_notify__field_descriptors,
  move_notify__field_indices_by_name,
  1,  move_notify__number_ranges,
  (ProtobufCMessageInit) move_notify__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sync_player_pos_notify__field_descriptors[4] =
{
  {
    "player_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SyncPlayerPosNotify, player_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_x",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SyncPlayerPosNotify, pos_x),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_z",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SyncPlayerPosNotify, pos_z),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scene_id",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SyncPlayerPosNotify, scene_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sync_player_pos_notify__field_indices_by_name[] = {
  0,   /* field[0] = player_id */
  1,   /* field[1] = pos_x */
  2,   /* field[2] = pos_z */
  3,   /* field[3] = scene_id */
};
static const ProtobufCIntRange sync_player_pos_notify__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor sync_player_pos_notify__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "sync_player_pos_notify",
  "SyncPlayerPosNotify",
  "SyncPlayerPosNotify",
  "",
  sizeof(SyncPlayerPosNotify),
  4,
  sync_player_pos_notify__field_descriptors,
  sync_player_pos_notify__field_indices_by_name,
  1,  sync_player_pos_notify__number_ranges,
  (ProtobufCMessageInit) sync_player_pos_notify__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sight_player_base_info__field_descriptors[28] =
{
  {
    "playerid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPlayerBaseInfo, playerid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(SightPlayerBaseInfo, n_data),
    PROTOBUF_C_OFFSETOF(SightPlayerBaseInfo, data),
    &pos_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPlayerBaseInfo, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lv",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPlayerBaseInfo, lv),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "job",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPlayerBaseInfo, job),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "avatar",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPlayerBaseInfo, avatar),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "direct_x",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPlayerBaseInfo, direct_x),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "direct_y",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPlayerBaseInfo, direct_y),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "direct_z",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPlayerBaseInfo, direct_z),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "speed",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPlayerBaseInfo, speed),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hp",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPlayerBaseInfo, hp),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "icon",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPlayerBaseInfo, icon),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maxhp",
    13,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPlayerBaseInfo, maxhp),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "clothes",
    14,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPlayerBaseInfo, clothes),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "clothes_color_up",
    15,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPlayerBaseInfo, clothes_color_up),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "clothes_color_down",
    16,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPlayerBaseInfo, clothes_color_down),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hat",
    17,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPlayerBaseInfo, hat),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hat_color",
    18,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPlayerBaseInfo, hat_color),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "buff_info",
    19,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(SightPlayerBaseInfo, n_buff_info),
    PROTOBUF_C_OFFSETOF(SightPlayerBaseInfo, buff_info),
    &buff_info__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "team_id",
    20,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPlayerBaseInfo, team_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fashion_weapon",
    21,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPlayerBaseInfo, fashion_weapon),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "horse",
    22,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPlayerBaseInfo, horse),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_y",
    23,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPlayerBaseInfo, pos_y),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pk_type",
    24,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPlayerBaseInfo, pk_type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "region_id",
    25,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPlayerBaseInfo, region_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "zhenying_id",
    26,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPlayerBaseInfo, zhenying_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "guild_id",
    27,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPlayerBaseInfo, guild_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fashion_weapon_color",
    28,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPlayerBaseInfo, fashion_weapon_color),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sight_player_base_info__field_indices_by_name[] = {
  5,   /* field[5] = avatar */
  18,   /* field[18] = buff_info */
  13,   /* field[13] = clothes */
  15,   /* field[15] = clothes_color_down */
  14,   /* field[14] = clothes_color_up */
  1,   /* field[1] = data */
  6,   /* field[6] = direct_x */
  7,   /* field[7] = direct_y */
  8,   /* field[8] = direct_z */
  20,   /* field[20] = fashion_weapon */
  27,   /* field[27] = fashion_weapon_color */
  26,   /* field[26] = guild_id */
  16,   /* field[16] = hat */
  17,   /* field[17] = hat_color */
  21,   /* field[21] = horse */
  10,   /* field[10] = hp */
  11,   /* field[11] = icon */
  4,   /* field[4] = job */
  3,   /* field[3] = lv */
  12,   /* field[12] = maxhp */
  2,   /* field[2] = name */
  23,   /* field[23] = pk_type */
  0,   /* field[0] = playerid */
  22,   /* field[22] = pos_y */
  24,   /* field[24] = region_id */
  9,   /* field[9] = speed */
  19,   /* field[19] = team_id */
  25,   /* field[25] = zhenying_id */
};
static const ProtobufCIntRange sight_player_base_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 28 }
};
const ProtobufCMessageDescriptor sight_player_base_info__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "sight_player_base_info",
  "SightPlayerBaseInfo",
  "SightPlayerBaseInfo",
  "",
  sizeof(SightPlayerBaseInfo),
  28,
  sight_player_base_info__field_descriptors,
  sight_player_base_info__field_indices_by_name,
  1,  sight_player_base_info__number_ranges,
  (ProtobufCMessageInit) sight_player_base_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sight_monster_info__field_descriptors[10] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightMonsterInfo, uuid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "monsterid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightMonsterInfo, monsterid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hp",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightMonsterInfo, hp),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(SightMonsterInfo, n_data),
    PROTOBUF_C_OFFSETOF(SightMonsterInfo, data),
    &pos_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "speed",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightMonsterInfo, speed),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lv",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightMonsterInfo, lv),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "buff_info",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(SightMonsterInfo, n_buff_info),
    PROTOBUF_C_OFFSETOF(SightMonsterInfo, buff_info),
    &buff_info__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pk_type",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightMonsterInfo, pk_type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "zhenying_id",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightMonsterInfo, zhenying_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "effectid",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightMonsterInfo, effectid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sight_monster_info__field_indices_by_name[] = {
  6,   /* field[6] = buff_info */
  3,   /* field[3] = data */
  9,   /* field[9] = effectid */
  2,   /* field[2] = hp */
  5,   /* field[5] = lv */
  1,   /* field[1] = monsterid */
  7,   /* field[7] = pk_type */
  4,   /* field[4] = speed */
  0,   /* field[0] = uuid */
  8,   /* field[8] = zhenying_id */
};
static const ProtobufCIntRange sight_monster_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor sight_monster_info__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "sight_monster_info",
  "SightMonsterInfo",
  "SightMonsterInfo",
  "",
  sizeof(SightMonsterInfo),
  10,
  sight_monster_info__field_descriptors,
  sight_monster_info__field_indices_by_name,
  1,  sight_monster_info__number_ranges,
  (ProtobufCMessageInit) sight_monster_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor player_on_cash_truck_info__field_descriptors[16] =
{
  {
    "playerid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PlayerOnCashTruckInfo, playerid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PlayerOnCashTruckInfo, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lv",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PlayerOnCashTruckInfo, lv),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "job",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PlayerOnCashTruckInfo, job),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "avatar",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PlayerOnCashTruckInfo, avatar),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hp",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PlayerOnCashTruckInfo, hp),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maxhp",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PlayerOnCashTruckInfo, maxhp),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "clothes",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PlayerOnCashTruckInfo, clothes),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "clothes_color_up",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PlayerOnCashTruckInfo, clothes_color_up),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "clothes_color_down",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PlayerOnCashTruckInfo, clothes_color_down),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hat",
    13,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PlayerOnCashTruckInfo, hat),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hat_color",
    14,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PlayerOnCashTruckInfo, hat_color),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "team_id",
    15,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PlayerOnCashTruckInfo, team_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fashion_weapon",
    16,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PlayerOnCashTruckInfo, fashion_weapon),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pk_type",
    17,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PlayerOnCashTruckInfo, pk_type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "region_id",
    18,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PlayerOnCashTruckInfo, region_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned player_on_cash_truck_info__field_indices_by_name[] = {
  4,   /* field[4] = avatar */
  7,   /* field[7] = clothes */
  9,   /* field[9] = clothes_color_down */
  8,   /* field[8] = clothes_color_up */
  13,   /* field[13] = fashion_weapon */
  10,   /* field[10] = hat */
  11,   /* field[11] = hat_color */
  5,   /* field[5] = hp */
  3,   /* field[3] = job */
  2,   /* field[2] = lv */
  6,   /* field[6] = maxhp */
  1,   /* field[1] = name */
  14,   /* field[14] = pk_type */
  0,   /* field[0] = playerid */
  15,   /* field[15] = region_id */
  12,   /* field[12] = team_id */
};
static const ProtobufCIntRange player_on_cash_truck_info__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 3, 1 },
  { 9, 6 },
  { 0, 16 }
};
const ProtobufCMessageDescriptor player_on_cash_truck_info__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "player_on_cash_truck_info",
  "PlayerOnCashTruckInfo",
  "PlayerOnCashTruckInfo",
  "",
  sizeof(PlayerOnCashTruckInfo),
  16,
  player_on_cash_truck_info__field_descriptors,
  player_on_cash_truck_info__field_indices_by_name,
  3,  player_on_cash_truck_info__number_ranges,
  (ProtobufCMessageInit) player_on_cash_truck_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sight_cash_truck_info__field_descriptors[17] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightCashTruckInfo, uuid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "monsterid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightCashTruckInfo, monsterid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hp",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightCashTruckInfo, hp),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(SightCashTruckInfo, n_data),
    PROTOBUF_C_OFFSETOF(SightCashTruckInfo, data),
    &pos_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "speed",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightCashTruckInfo, speed),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lv",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightCashTruckInfo, lv),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "buff_info",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(SightCashTruckInfo, n_buff_info),
    PROTOBUF_C_OFFSETOF(SightCashTruckInfo, buff_info),
    &buff_info__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "guild_id",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightCashTruckInfo, guild_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "owner",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightCashTruckInfo, owner),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "owner_name",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightCashTruckInfo, owner_name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "team_id",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightCashTruckInfo, team_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "zhenying_id",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightCashTruckInfo, zhenying_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maxhp",
    13,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightCashTruckInfo, maxhp),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_y",
    14,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightCashTruckInfo, pos_y),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pk_type",
    15,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightCashTruckInfo, pk_type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "direct_x",
    16,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightCashTruckInfo, direct_x),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "direct_z",
    17,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightCashTruckInfo, direct_z),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sight_cash_truck_info__field_indices_by_name[] = {
  6,   /* field[6] = buff_info */
  3,   /* field[3] = data */
  15,   /* field[15] = direct_x */
  16,   /* field[16] = direct_z */
  7,   /* field[7] = guild_id */
  2,   /* field[2] = hp */
  5,   /* field[5] = lv */
  12,   /* field[12] = maxhp */
  1,   /* field[1] = monsterid */
  8,   /* field[8] = owner */
  9,   /* field[9] = owner_name */
  14,   /* field[14] = pk_type */
  13,   /* field[13] = pos_y */
  4,   /* field[4] = speed */
  10,   /* field[10] = team_id */
  0,   /* field[0] = uuid */
  11,   /* field[11] = zhenying_id */
};
static const ProtobufCIntRange sight_cash_truck_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 17 }
};
const ProtobufCMessageDescriptor sight_cash_truck_info__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "sight_cash_truck_info",
  "SightCashTruckInfo",
  "SightCashTruckInfo",
  "",
  sizeof(SightCashTruckInfo),
  17,
  sight_cash_truck_info__field_descriptors,
  sight_cash_truck_info__field_indices_by_name,
  1,  sight_cash_truck_info__number_ranges,
  (ProtobufCMessageInit) sight_cash_truck_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sight_collect_info__field_descriptors[5] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightCollectInfo, uuid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "collectid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightCollectInfo, collectid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightCollectInfo, data),
    &pos_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightCollectInfo, y),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "yaw",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightCollectInfo, yaw),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sight_collect_info__field_indices_by_name[] = {
  1,   /* field[1] = collectid */
  2,   /* field[2] = data */
  0,   /* field[0] = uuid */
  3,   /* field[3] = y */
  4,   /* field[4] = yaw */
};
static const ProtobufCIntRange sight_collect_info__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 4, 2 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor sight_collect_info__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "sight_collect_info",
  "SightCollectInfo",
  "SightCollectInfo",
  "",
  sizeof(SightCollectInfo),
  5,
  sight_collect_info__field_descriptors,
  sight_collect_info__field_indices_by_name,
  2,  sight_collect_info__number_ranges,
  (ProtobufCMessageInit) sight_collect_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sight_npc_info__field_descriptors[4] =
{
  {
    "npcid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightNpcInfo, npcid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightNpcInfo, data),
    &pos_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cd",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightNpcInfo, cd),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightNpcInfo, y),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sight_npc_info__field_indices_by_name[] = {
  2,   /* field[2] = cd */
  1,   /* field[1] = data */
  0,   /* field[0] = npcid */
  3,   /* field[3] = y */
};
static const ProtobufCIntRange sight_npc_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor sight_npc_info__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "sight_npc_info",
  "SightNpcInfo",
  "SightNpcInfo",
  "",
  sizeof(SightNpcInfo),
  4,
  sight_npc_info__field_descriptors,
  sight_npc_info__field_indices_by_name,
  1,  sight_npc_info__number_ranges,
  (ProtobufCMessageInit) sight_npc_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sight_trap_info__field_descriptors[3] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightTrapInfo, uuid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "monsterid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightTrapInfo, monsterid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "owner",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightTrapInfo, owner),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sight_trap_info__field_indices_by_name[] = {
  1,   /* field[1] = monsterid */
  2,   /* field[2] = owner */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange sight_trap_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sight_trap_info__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "sight_trap_info",
  "SightTrapInfo",
  "SightTrapInfo",
  "",
  sizeof(SightTrapInfo),
  3,
  sight_trap_info__field_descriptors,
  sight_trap_info__field_indices_by_name,
  1,  sight_trap_info__number_ranges,
  (ProtobufCMessageInit) sight_trap_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sight_partner_info__field_descriptors[11] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPartnerInfo, uuid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "partnerid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPartnerInfo, partnerid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "owner",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPartnerInfo, owner),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hp",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPartnerInfo, hp),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(SightPartnerInfo, n_data),
    PROTOBUF_C_OFFSETOF(SightPartnerInfo, data),
    &pos_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "speed",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPartnerInfo, speed),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lv",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPartnerInfo, lv),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "buff_info",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(SightPartnerInfo, n_buff_info),
    PROTOBUF_C_OFFSETOF(SightPartnerInfo, buff_info),
    &buff_info__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pk_type",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPartnerInfo, pk_type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "zhenying_id",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPartnerInfo, zhenying_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maxhp",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPartnerInfo, maxhp),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sight_partner_info__field_indices_by_name[] = {
  7,   /* field[7] = buff_info */
  4,   /* field[4] = data */
  3,   /* field[3] = hp */
  6,   /* field[6] = lv */
  10,   /* field[10] = maxhp */
  2,   /* field[2] = owner */
  1,   /* field[1] = partnerid */
  8,   /* field[8] = pk_type */
  5,   /* field[5] = speed */
  0,   /* field[0] = uuid */
  9,   /* field[9] = zhenying_id */
};
static const ProtobufCIntRange sight_partner_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor sight_partner_info__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "sight_partner_info",
  "SightPartnerInfo",
  "SightPartnerInfo",
  "",
  sizeof(SightPartnerInfo),
  11,
  sight_partner_info__field_descriptors,
  sight_partner_info__field_indices_by_name,
  1,  sight_partner_info__number_ranges,
  (ProtobufCMessageInit) sight_partner_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sight_changed_notify__field_descriptors[12] =
{
  {
    "add_player",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(SightChangedNotify, n_add_player),
    PROTOBUF_C_OFFSETOF(SightChangedNotify, add_player),
    &sight_player_base_info__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "delete_player",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(SightChangedNotify, n_delete_player),
    PROTOBUF_C_OFFSETOF(SightChangedNotify, delete_player),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "add_monster",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(SightChangedNotify, n_add_monster),
    PROTOBUF_C_OFFSETOF(SightChangedNotify, add_monster),
    &sight_monster_info__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "delete_monster",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(SightChangedNotify, n_delete_monster),
    PROTOBUF_C_OFFSETOF(SightChangedNotify, delete_monster),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "add_trap",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(SightChangedNotify, n_add_trap),
    PROTOBUF_C_OFFSETOF(SightChangedNotify, add_trap),
    &sight_trap_info__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "delete_trap",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(SightChangedNotify, n_delete_trap),
    PROTOBUF_C_OFFSETOF(SightChangedNotify, delete_trap),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "add_collect",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(SightChangedNotify, n_add_collect),
    PROTOBUF_C_OFFSETOF(SightChangedNotify, add_collect),
    &sight_collect_info__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "delete_collect",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(SightChangedNotify, n_delete_collect),
    PROTOBUF_C_OFFSETOF(SightChangedNotify, delete_collect),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "add_cash_truck",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(SightChangedNotify, n_add_cash_truck),
    PROTOBUF_C_OFFSETOF(SightChangedNotify, add_cash_truck),
    &sight_cash_truck_info__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "delete_cash_truck",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(SightChangedNotify, n_delete_cash_truck),
    PROTOBUF_C_OFFSETOF(SightChangedNotify, delete_cash_truck),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "add_partner",
    11,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(SightChangedNotify, n_add_partner),
    PROTOBUF_C_OFFSETOF(SightChangedNotify, add_partner),
    &sight_partner_info__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "delete_partner",
    12,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(SightChangedNotify, n_delete_partner),
    PROTOBUF_C_OFFSETOF(SightChangedNotify, delete_partner),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sight_changed_notify__field_indices_by_name[] = {
  8,   /* field[8] = add_cash_truck */
  6,   /* field[6] = add_collect */
  2,   /* field[2] = add_monster */
  10,   /* field[10] = add_partner */
  0,   /* field[0] = add_player */
  4,   /* field[4] = add_trap */
  9,   /* field[9] = delete_cash_truck */
  7,   /* field[7] = delete_collect */
  3,   /* field[3] = delete_monster */
  11,   /* field[11] = delete_partner */
  1,   /* field[1] = delete_player */
  5,   /* field[5] = delete_trap */
};
static const ProtobufCIntRange sight_changed_notify__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor sight_changed_notify__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "sight_changed_notify",
  "SightChangedNotify",
  "SightChangedNotify",
  "",
  sizeof(SightChangedNotify),
  12,
  sight_changed_notify__field_descriptors,
  sight_changed_notify__field_indices_by_name,
  1,  sight_changed_notify__number_ranges,
  (ProtobufCMessageInit) sight_changed_notify__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor special_monster_pos_notify__field_descriptors[5] =
{
  {
    "monster_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SpecialMonsterPosNotify, monster_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uuid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SpecialMonsterPosNotify, uuid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scene_id",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SpecialMonsterPosNotify, scene_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_x",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SpecialMonsterPosNotify, pos_x),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_z",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SpecialMonsterPosNotify, pos_z),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned special_monster_pos_notify__field_indices_by_name[] = {
  0,   /* field[0] = monster_id */
  3,   /* field[3] = pos_x */
  4,   /* field[4] = pos_z */
  2,   /* field[2] = scene_id */
  1,   /* field[1] = uuid */
};
static const ProtobufCIntRange special_monster_pos_notify__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor special_monster_pos_notify__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "special_monster_pos_notify",
  "SpecialMonsterPosNotify",
  "SpecialMonsterPosNotify",
  "",
  sizeof(SpecialMonsterPosNotify),
  5,
  special_monster_pos_notify__field_descriptors,
  special_monster_pos_notify__field_indices_by_name,
  1,  special_monster_pos_notify__number_ranges,
  (ProtobufCMessageInit) special_monster_pos_notify__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor special_player_pos_notify__field_descriptors[4] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SpecialPlayerPosNotify, uuid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scene_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SpecialPlayerPosNotify, scene_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_x",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SpecialPlayerPosNotify, pos_x),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_z",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SpecialPlayerPosNotify, pos_z),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned special_player_pos_notify__field_indices_by_name[] = {
  2,   /* field[2] = pos_x */
  3,   /* field[3] = pos_z */
  1,   /* field[1] = scene_id */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange special_player_pos_notify__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor special_player_pos_notify__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "special_player_pos_notify",
  "SpecialPlayerPosNotify",
  "SpecialPlayerPosNotify",
  "",
  sizeof(SpecialPlayerPosNotify),
  4,
  special_player_pos_notify__field_descriptors,
  special_player_pos_notify__field_indices_by_name,
  1,  special_player_pos_notify__number_ranges,
  (ProtobufCMessageInit) special_player_pos_notify__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sight_player_info_change_notify__field_descriptors[2] =
{
  {
    "player_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightPlayerInfoChangeNotify, player_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "guild_id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(SightPlayerInfoChangeNotify, has_guild_id),
    PROTOBUF_C_OFFSETOF(SightPlayerInfoChangeNotify, guild_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sight_player_info_change_notify__field_indices_by_name[] = {
  1,   /* field[1] = guild_id */
  0,   /* field[0] = player_id */
};
static const ProtobufCIntRange sight_player_info_change_notify__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sight_player_info_change_notify__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "sight_player_info_change_notify",
  "SightPlayerInfoChangeNotify",
  "SightPlayerInfoChangeNotify",
  "",
  sizeof(SightPlayerInfoChangeNotify),
  2,
  sight_player_info_change_notify__field_descriptors,
  sight_player_info_change_notify__field_indices_by_name,
  1,  sight_player_info_change_notify__number_ranges,
  (ProtobufCMessageInit) sight_player_info_change_notify__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sight_monster_id_change_notify__field_descriptors[2] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightMonsterIdChangeNotify, uuid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "monster_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SightMonsterIdChangeNotify, monster_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sight_monster_id_change_notify__field_indices_by_name[] = {
  1,   /* field[1] = monster_id */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange sight_monster_id_change_notify__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sight_monster_id_change_notify__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "sight_monster_id_change_notify",
  "SightMonsterIdChangeNotify",
  "SightMonsterIdChangeNotify",
  "",
  sizeof(SightMonsterIdChangeNotify),
  2,
  sight_monster_id_change_notify__field_descriptors,
  sight_monster_id_change_notify__field_indices_by_name,
  1,  sight_monster_id_change_notify__number_ranges,
  (ProtobufCMessageInit) sight_monster_id_change_notify__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor monster_talk_notify__field_descriptors[2] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MonsterTalkNotify, uuid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "talkid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MonsterTalkNotify, talkid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned monster_talk_notify__field_indices_by_name[] = {
  1,   /* field[1] = talkid */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange monster_talk_notify__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor monster_talk_notify__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "monster_talk_notify",
  "MonsterTalkNotify",
  "MonsterTalkNotify",
  "",
  sizeof(MonsterTalkNotify),
  2,
  monster_talk_notify__field_descriptors,
  monster_talk_notify__field_indices_by_name,
  1,  monster_talk_notify__number_ranges,
  (ProtobufCMessageInit) monster_talk_notify__init,
  NULL,NULL,NULL    /* reserved[123] */
};
