/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "partner.pb-c.h"
void   partner_skill_data__init
                     (PartnerSkillData         *message)
{
  static PartnerSkillData init_value = PARTNER_SKILL_DATA__INIT;
  *message = init_value;
}
size_t partner_skill_data__get_packed_size
                     (const PartnerSkillData *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_skill_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t partner_skill_data__pack
                     (const PartnerSkillData *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_skill_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t partner_skill_data__pack_to_buffer
                     (const PartnerSkillData *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_skill_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PartnerSkillData *
       partner_skill_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PartnerSkillData *)
     protobuf_c_message_unpack (&partner_skill_data__descriptor,
                                allocator, len, data);
}
void   partner_skill_data__free_unpacked
                     (PartnerSkillData *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_skill_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   partner_attr__init
                     (PartnerAttr         *message)
{
  static PartnerAttr init_value = PARTNER_ATTR__INIT;
  *message = init_value;
}
size_t partner_attr__get_packed_size
                     (const PartnerAttr *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_attr__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t partner_attr__pack
                     (const PartnerAttr *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_attr__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t partner_attr__pack_to_buffer
                     (const PartnerAttr *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_attr__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PartnerAttr *
       partner_attr__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PartnerAttr *)
     protobuf_c_message_unpack (&partner_attr__descriptor,
                                allocator, len, data);
}
void   partner_attr__free_unpacked
                     (PartnerAttr *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_attr__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   partner_data__init
                     (PartnerData         *message)
{
  static PartnerData init_value = PARTNER_DATA__INIT;
  *message = init_value;
}
size_t partner_data__get_packed_size
                     (const PartnerData *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t partner_data__pack
                     (const PartnerData *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t partner_data__pack_to_buffer
                     (const PartnerData *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PartnerData *
       partner_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PartnerData *)
     protobuf_c_message_unpack (&partner_data__descriptor,
                                allocator, len, data);
}
void   partner_data__free_unpacked
                     (PartnerData *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   partner_info_answer__init
                     (PartnerInfoAnswer         *message)
{
  static PartnerInfoAnswer init_value = PARTNER_INFO_ANSWER__INIT;
  *message = init_value;
}
size_t partner_info_answer__get_packed_size
                     (const PartnerInfoAnswer *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_info_answer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t partner_info_answer__pack
                     (const PartnerInfoAnswer *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_info_answer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t partner_info_answer__pack_to_buffer
                     (const PartnerInfoAnswer *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_info_answer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PartnerInfoAnswer *
       partner_info_answer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PartnerInfoAnswer *)
     protobuf_c_message_unpack (&partner_info_answer__descriptor,
                                allocator, len, data);
}
void   partner_info_answer__free_unpacked
                     (PartnerInfoAnswer *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_info_answer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   partner_turn_switch_request__init
                     (PartnerTurnSwitchRequest         *message)
{
  static PartnerTurnSwitchRequest init_value = PARTNER_TURN_SWITCH_REQUEST__INIT;
  *message = init_value;
}
size_t partner_turn_switch_request__get_packed_size
                     (const PartnerTurnSwitchRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_turn_switch_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t partner_turn_switch_request__pack
                     (const PartnerTurnSwitchRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_turn_switch_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t partner_turn_switch_request__pack_to_buffer
                     (const PartnerTurnSwitchRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_turn_switch_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PartnerTurnSwitchRequest *
       partner_turn_switch_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PartnerTurnSwitchRequest *)
     protobuf_c_message_unpack (&partner_turn_switch_request__descriptor,
                                allocator, len, data);
}
void   partner_turn_switch_request__free_unpacked
                     (PartnerTurnSwitchRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_turn_switch_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   partner_formation_request__init
                     (PartnerFormationRequest         *message)
{
  static PartnerFormationRequest init_value = PARTNER_FORMATION_REQUEST__INIT;
  *message = init_value;
}
size_t partner_formation_request__get_packed_size
                     (const PartnerFormationRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_formation_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t partner_formation_request__pack
                     (const PartnerFormationRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_formation_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t partner_formation_request__pack_to_buffer
                     (const PartnerFormationRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_formation_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PartnerFormationRequest *
       partner_formation_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PartnerFormationRequest *)
     protobuf_c_message_unpack (&partner_formation_request__descriptor,
                                allocator, len, data);
}
void   partner_formation_request__free_unpacked
                     (PartnerFormationRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_formation_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   partner_formation_answer__init
                     (PartnerFormationAnswer         *message)
{
  static PartnerFormationAnswer init_value = PARTNER_FORMATION_ANSWER__INIT;
  *message = init_value;
}
size_t partner_formation_answer__get_packed_size
                     (const PartnerFormationAnswer *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_formation_answer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t partner_formation_answer__pack
                     (const PartnerFormationAnswer *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_formation_answer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t partner_formation_answer__pack_to_buffer
                     (const PartnerFormationAnswer *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_formation_answer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PartnerFormationAnswer *
       partner_formation_answer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PartnerFormationAnswer *)
     protobuf_c_message_unpack (&partner_formation_answer__descriptor,
                                allocator, len, data);
}
void   partner_formation_answer__free_unpacked
                     (PartnerFormationAnswer *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_formation_answer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   partner_learn_skill_request__init
                     (PartnerLearnSkillRequest         *message)
{
  static PartnerLearnSkillRequest init_value = PARTNER_LEARN_SKILL_REQUEST__INIT;
  *message = init_value;
}
size_t partner_learn_skill_request__get_packed_size
                     (const PartnerLearnSkillRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_learn_skill_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t partner_learn_skill_request__pack
                     (const PartnerLearnSkillRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_learn_skill_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t partner_learn_skill_request__pack_to_buffer
                     (const PartnerLearnSkillRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_learn_skill_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PartnerLearnSkillRequest *
       partner_learn_skill_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PartnerLearnSkillRequest *)
     protobuf_c_message_unpack (&partner_learn_skill_request__descriptor,
                                allocator, len, data);
}
void   partner_learn_skill_request__free_unpacked
                     (PartnerLearnSkillRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_learn_skill_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   partner_learn_skill_answer__init
                     (PartnerLearnSkillAnswer         *message)
{
  static PartnerLearnSkillAnswer init_value = PARTNER_LEARN_SKILL_ANSWER__INIT;
  *message = init_value;
}
size_t partner_learn_skill_answer__get_packed_size
                     (const PartnerLearnSkillAnswer *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_learn_skill_answer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t partner_learn_skill_answer__pack
                     (const PartnerLearnSkillAnswer *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_learn_skill_answer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t partner_learn_skill_answer__pack_to_buffer
                     (const PartnerLearnSkillAnswer *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_learn_skill_answer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PartnerLearnSkillAnswer *
       partner_learn_skill_answer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PartnerLearnSkillAnswer *)
     protobuf_c_message_unpack (&partner_learn_skill_answer__descriptor,
                                allocator, len, data);
}
void   partner_learn_skill_answer__free_unpacked
                     (PartnerLearnSkillAnswer *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_learn_skill_answer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   partner_use_exp_item_request__init
                     (PartnerUseExpItemRequest         *message)
{
  static PartnerUseExpItemRequest init_value = PARTNER_USE_EXP_ITEM_REQUEST__INIT;
  *message = init_value;
}
size_t partner_use_exp_item_request__get_packed_size
                     (const PartnerUseExpItemRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_use_exp_item_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t partner_use_exp_item_request__pack
                     (const PartnerUseExpItemRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_use_exp_item_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t partner_use_exp_item_request__pack_to_buffer
                     (const PartnerUseExpItemRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_use_exp_item_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PartnerUseExpItemRequest *
       partner_use_exp_item_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PartnerUseExpItemRequest *)
     protobuf_c_message_unpack (&partner_use_exp_item_request__descriptor,
                                allocator, len, data);
}
void   partner_use_exp_item_request__free_unpacked
                     (PartnerUseExpItemRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_use_exp_item_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   partner_add_base_attr__init
                     (PartnerAddBaseAttr         *message)
{
  static PartnerAddBaseAttr init_value = PARTNER_ADD_BASE_ATTR__INIT;
  *message = init_value;
}
size_t partner_add_base_attr__get_packed_size
                     (const PartnerAddBaseAttr *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_add_base_attr__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t partner_add_base_attr__pack
                     (const PartnerAddBaseAttr *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_add_base_attr__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t partner_add_base_attr__pack_to_buffer
                     (const PartnerAddBaseAttr *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_add_base_attr__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PartnerAddBaseAttr *
       partner_add_base_attr__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PartnerAddBaseAttr *)
     protobuf_c_message_unpack (&partner_add_base_attr__descriptor,
                                allocator, len, data);
}
void   partner_add_base_attr__free_unpacked
                     (PartnerAddBaseAttr *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_add_base_attr__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   partner_dismiss_request__init
                     (PartnerDismissRequest         *message)
{
  static PartnerDismissRequest init_value = PARTNER_DISMISS_REQUEST__INIT;
  *message = init_value;
}
size_t partner_dismiss_request__get_packed_size
                     (const PartnerDismissRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_dismiss_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t partner_dismiss_request__pack
                     (const PartnerDismissRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_dismiss_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t partner_dismiss_request__pack_to_buffer
                     (const PartnerDismissRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_dismiss_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PartnerDismissRequest *
       partner_dismiss_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PartnerDismissRequest *)
     protobuf_c_message_unpack (&partner_dismiss_request__descriptor,
                                allocator, len, data);
}
void   partner_dismiss_request__free_unpacked
                     (PartnerDismissRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_dismiss_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   partner_uuid__init
                     (PartnerUuid         *message)
{
  static PartnerUuid init_value = PARTNER_UUID__INIT;
  *message = init_value;
}
size_t partner_uuid__get_packed_size
                     (const PartnerUuid *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_uuid__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t partner_uuid__pack
                     (const PartnerUuid *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_uuid__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t partner_uuid__pack_to_buffer
                     (const PartnerUuid *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_uuid__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PartnerUuid *
       partner_uuid__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PartnerUuid *)
     protobuf_c_message_unpack (&partner_uuid__descriptor,
                                allocator, len, data);
}
void   partner_uuid__free_unpacked
                     (PartnerUuid *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_uuid__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   res_reset_attr__init
                     (ResResetAttr         *message)
{
  static ResResetAttr init_value = RES_RESET_ATTR__INIT;
  *message = init_value;
}
size_t res_reset_attr__get_packed_size
                     (const ResResetAttr *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &res_reset_attr__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t res_reset_attr__pack
                     (const ResResetAttr *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &res_reset_attr__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t res_reset_attr__pack_to_buffer
                     (const ResResetAttr *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &res_reset_attr__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ResResetAttr *
       res_reset_attr__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ResResetAttr *)
     protobuf_c_message_unpack (&res_reset_attr__descriptor,
                                allocator, len, data);
}
void   res_reset_attr__free_unpacked
                     (ResResetAttr *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &res_reset_attr__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   strong_partner__init
                     (StrongPartner         *message)
{
  static StrongPartner init_value = STRONG_PARTNER__INIT;
  *message = init_value;
}
size_t strong_partner__get_packed_size
                     (const StrongPartner *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &strong_partner__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t strong_partner__pack
                     (const StrongPartner *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &strong_partner__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t strong_partner__pack_to_buffer
                     (const StrongPartner *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &strong_partner__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StrongPartner *
       strong_partner__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StrongPartner *)
     protobuf_c_message_unpack (&strong_partner__descriptor,
                                allocator, len, data);
}
void   strong_partner__free_unpacked
                     (StrongPartner *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &strong_partner__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   res_strong_partner__init
                     (ResStrongPartner         *message)
{
  static ResStrongPartner init_value = RES_STRONG_PARTNER__INIT;
  *message = init_value;
}
size_t res_strong_partner__get_packed_size
                     (const ResStrongPartner *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &res_strong_partner__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t res_strong_partner__pack
                     (const ResStrongPartner *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &res_strong_partner__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t res_strong_partner__pack_to_buffer
                     (const ResStrongPartner *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &res_strong_partner__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ResStrongPartner *
       res_strong_partner__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ResStrongPartner *)
     protobuf_c_message_unpack (&res_strong_partner__descriptor,
                                allocator, len, data);
}
void   res_strong_partner__free_unpacked
                     (ResStrongPartner *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &res_strong_partner__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   partner_dismiss_answer__init
                     (PartnerDismissAnswer         *message)
{
  static PartnerDismissAnswer init_value = PARTNER_DISMISS_ANSWER__INIT;
  *message = init_value;
}
size_t partner_dismiss_answer__get_packed_size
                     (const PartnerDismissAnswer *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_dismiss_answer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t partner_dismiss_answer__pack
                     (const PartnerDismissAnswer *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_dismiss_answer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t partner_dismiss_answer__pack_to_buffer
                     (const PartnerDismissAnswer *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_dismiss_answer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PartnerDismissAnswer *
       partner_dismiss_answer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PartnerDismissAnswer *)
     protobuf_c_message_unpack (&partner_dismiss_answer__descriptor,
                                allocator, len, data);
}
void   partner_dismiss_answer__free_unpacked
                     (PartnerDismissAnswer *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_dismiss_answer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   partner_dictionary_add_notify__init
                     (PartnerDictionaryAddNotify         *message)
{
  static PartnerDictionaryAddNotify init_value = PARTNER_DICTIONARY_ADD_NOTIFY__INIT;
  *message = init_value;
}
size_t partner_dictionary_add_notify__get_packed_size
                     (const PartnerDictionaryAddNotify *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_dictionary_add_notify__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t partner_dictionary_add_notify__pack
                     (const PartnerDictionaryAddNotify *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_dictionary_add_notify__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t partner_dictionary_add_notify__pack_to_buffer
                     (const PartnerDictionaryAddNotify *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_dictionary_add_notify__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PartnerDictionaryAddNotify *
       partner_dictionary_add_notify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PartnerDictionaryAddNotify *)
     protobuf_c_message_unpack (&partner_dictionary_add_notify__descriptor,
                                allocator, len, data);
}
void   partner_dictionary_add_notify__free_unpacked
                     (PartnerDictionaryAddNotify *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_dictionary_add_notify__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   partner_exchange_request__init
                     (PartnerExchangeRequest         *message)
{
  static PartnerExchangeRequest init_value = PARTNER_EXCHANGE_REQUEST__INIT;
  *message = init_value;
}
size_t partner_exchange_request__get_packed_size
                     (const PartnerExchangeRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_exchange_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t partner_exchange_request__pack
                     (const PartnerExchangeRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_exchange_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t partner_exchange_request__pack_to_buffer
                     (const PartnerExchangeRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_exchange_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PartnerExchangeRequest *
       partner_exchange_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PartnerExchangeRequest *)
     protobuf_c_message_unpack (&partner_exchange_request__descriptor,
                                allocator, len, data);
}
void   partner_exchange_request__free_unpacked
                     (PartnerExchangeRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_exchange_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   partner_exchange_answer__init
                     (PartnerExchangeAnswer         *message)
{
  static PartnerExchangeAnswer init_value = PARTNER_EXCHANGE_ANSWER__INIT;
  *message = init_value;
}
size_t partner_exchange_answer__get_packed_size
                     (const PartnerExchangeAnswer *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_exchange_answer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t partner_exchange_answer__pack
                     (const PartnerExchangeAnswer *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_exchange_answer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t partner_exchange_answer__pack_to_buffer
                     (const PartnerExchangeAnswer *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_exchange_answer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PartnerExchangeAnswer *
       partner_exchange_answer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PartnerExchangeAnswer *)
     protobuf_c_message_unpack (&partner_exchange_answer__descriptor,
                                allocator, len, data);
}
void   partner_exchange_answer__free_unpacked
                     (PartnerExchangeAnswer *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_exchange_answer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   partner_recruit_request__init
                     (PartnerRecruitRequest         *message)
{
  static PartnerRecruitRequest init_value = PARTNER_RECRUIT_REQUEST__INIT;
  *message = init_value;
}
size_t partner_recruit_request__get_packed_size
                     (const PartnerRecruitRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_recruit_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t partner_recruit_request__pack
                     (const PartnerRecruitRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_recruit_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t partner_recruit_request__pack_to_buffer
                     (const PartnerRecruitRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_recruit_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PartnerRecruitRequest *
       partner_recruit_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PartnerRecruitRequest *)
     protobuf_c_message_unpack (&partner_recruit_request__descriptor,
                                allocator, len, data);
}
void   partner_recruit_request__free_unpacked
                     (PartnerRecruitRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_recruit_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   partner_recruit_result_data__init
                     (PartnerRecruitResultData         *message)
{
  static PartnerRecruitResultData init_value = PARTNER_RECRUIT_RESULT_DATA__INIT;
  *message = init_value;
}
size_t partner_recruit_result_data__get_packed_size
                     (const PartnerRecruitResultData *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_recruit_result_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t partner_recruit_result_data__pack
                     (const PartnerRecruitResultData *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_recruit_result_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t partner_recruit_result_data__pack_to_buffer
                     (const PartnerRecruitResultData *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_recruit_result_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PartnerRecruitResultData *
       partner_recruit_result_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PartnerRecruitResultData *)
     protobuf_c_message_unpack (&partner_recruit_result_data__descriptor,
                                allocator, len, data);
}
void   partner_recruit_result_data__free_unpacked
                     (PartnerRecruitResultData *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_recruit_result_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   partner_recruit_answer__init
                     (PartnerRecruitAnswer         *message)
{
  static PartnerRecruitAnswer init_value = PARTNER_RECRUIT_ANSWER__INIT;
  *message = init_value;
}
size_t partner_recruit_answer__get_packed_size
                     (const PartnerRecruitAnswer *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_recruit_answer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t partner_recruit_answer__pack
                     (const PartnerRecruitAnswer *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_recruit_answer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t partner_recruit_answer__pack_to_buffer
                     (const PartnerRecruitAnswer *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_recruit_answer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PartnerRecruitAnswer *
       partner_recruit_answer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PartnerRecruitAnswer *)
     protobuf_c_message_unpack (&partner_recruit_answer__descriptor,
                                allocator, len, data);
}
void   partner_recruit_answer__free_unpacked
                     (PartnerRecruitAnswer *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &partner_recruit_answer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor partner_skill_data__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerSkillData, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lv",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerSkillData, lv),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned partner_skill_data__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = lv */
};
static const ProtobufCIntRange partner_skill_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor partner_skill_data__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PartnerSkillData",
  "PartnerSkillData",
  "PartnerSkillData",
  "",
  sizeof(PartnerSkillData),
  2,
  partner_skill_data__field_descriptors,
  partner_skill_data__field_indices_by_name,
  1,  partner_skill_data__number_ranges,
  (ProtobufCMessageInit) partner_skill_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor partner_attr__field_descriptors[7] =
{
  {
    "skills",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(PartnerAttr, n_skills),
    PROTOBUF_C_OFFSETOF(PartnerAttr, skills),
    &partner_skill_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "base_attr_id",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(PartnerAttr, n_base_attr_id),
    PROTOBUF_C_OFFSETOF(PartnerAttr, base_attr_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "base_attr_cur",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(PartnerAttr, n_base_attr_cur),
    PROTOBUF_C_OFFSETOF(PartnerAttr, base_attr_cur),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "base_attr_up",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(PartnerAttr, n_base_attr_up),
    PROTOBUF_C_OFFSETOF(PartnerAttr, base_attr_up),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "detail_attr_id",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(PartnerAttr, n_detail_attr_id),
    PROTOBUF_C_OFFSETOF(PartnerAttr, detail_attr_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "detail_attr_cur",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(PartnerAttr, n_detail_attr_cur),
    PROTOBUF_C_OFFSETOF(PartnerAttr, detail_attr_cur),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerAttr, type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned partner_attr__field_indices_by_name[] = {
  2,   /* field[2] = base_attr_cur */
  1,   /* field[1] = base_attr_id */
  3,   /* field[3] = base_attr_up */
  5,   /* field[5] = detail_attr_cur */
  4,   /* field[4] = detail_attr_id */
  0,   /* field[0] = skills */
  6,   /* field[6] = type */
};
static const ProtobufCIntRange partner_attr__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor partner_attr__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PartnerAttr",
  "PartnerAttr",
  "PartnerAttr",
  "",
  sizeof(PartnerAttr),
  7,
  partner_attr__field_descriptors,
  partner_attr__field_indices_by_name,
  1,  partner_attr__number_ranges,
  (ProtobufCMessageInit) partner_attr__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor partner_data__field_descriptors[8] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerData, uuid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "partnerId",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerData, partnerid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attrs",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(PartnerData, n_attrs),
    PROTOBUF_C_OFFSETOF(PartnerData, attrs),
    &attr_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cur_attr",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerData, cur_attr),
    &partner_attr__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flash_attr",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerData, flash_attr),
    &partner_attr__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "god_id",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(PartnerData, n_god_id),
    PROTOBUF_C_OFFSETOF(PartnerData, god_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "god_level",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(PartnerData, n_god_level),
    PROTOBUF_C_OFFSETOF(PartnerData, god_level),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "power",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerData, power),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned partner_data__field_indices_by_name[] = {
  2,   /* field[2] = attrs */
  3,   /* field[3] = cur_attr */
  4,   /* field[4] = flash_attr */
  5,   /* field[5] = god_id */
  6,   /* field[6] = god_level */
  1,   /* field[1] = partnerId */
  7,   /* field[7] = power */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange partner_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor partner_data__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PartnerData",
  "PartnerData",
  "PartnerData",
  "",
  sizeof(PartnerData),
  8,
  partner_data__field_descriptors,
  partner_data__field_indices_by_name,
  1,  partner_data__number_ranges,
  (ProtobufCMessageInit) partner_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor partner_info_answer__field_descriptors[8] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerInfoAnswer, result),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "partners",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(PartnerInfoAnswer, n_partners),
    PROTOBUF_C_OFFSETOF(PartnerInfoAnswer, partners),
    &partner_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "formation",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(PartnerInfoAnswer, n_formation),
    PROTOBUF_C_OFFSETOF(PartnerInfoAnswer, formation),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dictionary",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(PartnerInfoAnswer, n_dictionary),
    PROTOBUF_C_OFFSETOF(PartnerInfoAnswer, dictionary),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "recruitJuniorTime",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerInfoAnswer, recruitjuniortime),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "recruitJuniorCount",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerInfoAnswer, recruitjuniorcount),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "recruitSeniorTime",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerInfoAnswer, recruitseniortime),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "recruitSeniorCount",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerInfoAnswer, recruitseniorcount),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned partner_info_answer__field_indices_by_name[] = {
  3,   /* field[3] = dictionary */
  2,   /* field[2] = formation */
  1,   /* field[1] = partners */
  5,   /* field[5] = recruitJuniorCount */
  4,   /* field[4] = recruitJuniorTime */
  7,   /* field[7] = recruitSeniorCount */
  6,   /* field[6] = recruitSeniorTime */
  0,   /* field[0] = result */
};
static const ProtobufCIntRange partner_info_answer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor partner_info_answer__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PartnerInfoAnswer",
  "PartnerInfoAnswer",
  "PartnerInfoAnswer",
  "",
  sizeof(PartnerInfoAnswer),
  8,
  partner_info_answer__field_descriptors,
  partner_info_answer__field_indices_by_name,
  1,  partner_info_answer__number_ranges,
  (ProtobufCMessageInit) partner_info_answer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor partner_turn_switch_request__field_descriptors[1] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerTurnSwitchRequest, type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned partner_turn_switch_request__field_indices_by_name[] = {
  0,   /* field[0] = type */
};
static const ProtobufCIntRange partner_turn_switch_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor partner_turn_switch_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PartnerTurnSwitchRequest",
  "PartnerTurnSwitchRequest",
  "PartnerTurnSwitchRequest",
  "",
  sizeof(PartnerTurnSwitchRequest),
  1,
  partner_turn_switch_request__field_descriptors,
  partner_turn_switch_request__field_indices_by_name,
  1,  partner_turn_switch_request__number_ranges,
  (ProtobufCMessageInit) partner_turn_switch_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor partner_formation_request__field_descriptors[2] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerFormationRequest, uuid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerFormationRequest, position),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned partner_formation_request__field_indices_by_name[] = {
  1,   /* field[1] = position */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange partner_formation_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor partner_formation_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PartnerFormationRequest",
  "PartnerFormationRequest",
  "PartnerFormationRequest",
  "",
  sizeof(PartnerFormationRequest),
  2,
  partner_formation_request__field_descriptors,
  partner_formation_request__field_indices_by_name,
  1,  partner_formation_request__number_ranges,
  (ProtobufCMessageInit) partner_formation_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor partner_formation_answer__field_descriptors[2] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerFormationAnswer, result),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uuids",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(PartnerFormationAnswer, n_uuids),
    PROTOBUF_C_OFFSETOF(PartnerFormationAnswer, uuids),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned partner_formation_answer__field_indices_by_name[] = {
  0,   /* field[0] = result */
  1,   /* field[1] = uuids */
};
static const ProtobufCIntRange partner_formation_answer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor partner_formation_answer__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PartnerFormationAnswer",
  "PartnerFormationAnswer",
  "PartnerFormationAnswer",
  "",
  sizeof(PartnerFormationAnswer),
  2,
  partner_formation_answer__field_descriptors,
  partner_formation_answer__field_indices_by_name,
  1,  partner_formation_answer__number_ranges,
  (ProtobufCMessageInit) partner_formation_answer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor partner_learn_skill_request__field_descriptors[3] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerLearnSkillRequest, uuid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerLearnSkillRequest, index),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bookId",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerLearnSkillRequest, bookid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned partner_learn_skill_request__field_indices_by_name[] = {
  2,   /* field[2] = bookId */
  1,   /* field[1] = index */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange partner_learn_skill_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor partner_learn_skill_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PartnerLearnSkillRequest",
  "PartnerLearnSkillRequest",
  "PartnerLearnSkillRequest",
  "",
  sizeof(PartnerLearnSkillRequest),
  3,
  partner_learn_skill_request__field_descriptors,
  partner_learn_skill_request__field_indices_by_name,
  1,  partner_learn_skill_request__number_ranges,
  (ProtobufCMessageInit) partner_learn_skill_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor partner_learn_skill_answer__field_descriptors[4] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerLearnSkillAnswer, result),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uuid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerLearnSkillAnswer, uuid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerLearnSkillAnswer, index),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "skill",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerLearnSkillAnswer, skill),
    &partner_skill_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned partner_learn_skill_answer__field_indices_by_name[] = {
  2,   /* field[2] = index */
  0,   /* field[0] = result */
  3,   /* field[3] = skill */
  1,   /* field[1] = uuid */
};
static const ProtobufCIntRange partner_learn_skill_answer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor partner_learn_skill_answer__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PartnerLearnSkillAnswer",
  "PartnerLearnSkillAnswer",
  "PartnerLearnSkillAnswer",
  "",
  sizeof(PartnerLearnSkillAnswer),
  4,
  partner_learn_skill_answer__field_descriptors,
  partner_learn_skill_answer__field_indices_by_name,
  1,  partner_learn_skill_answer__number_ranges,
  (ProtobufCMessageInit) partner_learn_skill_answer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor partner_use_exp_item_request__field_descriptors[2] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerUseExpItemRequest, uuid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "itemId",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerUseExpItemRequest, itemid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned partner_use_exp_item_request__field_indices_by_name[] = {
  1,   /* field[1] = itemId */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange partner_use_exp_item_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor partner_use_exp_item_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PartnerUseExpItemRequest",
  "PartnerUseExpItemRequest",
  "PartnerUseExpItemRequest",
  "",
  sizeof(PartnerUseExpItemRequest),
  2,
  partner_use_exp_item_request__field_descriptors,
  partner_use_exp_item_request__field_indices_by_name,
  1,  partner_use_exp_item_request__number_ranges,
  (ProtobufCMessageInit) partner_use_exp_item_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor partner_add_base_attr__field_descriptors[3] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerAddBaseAttr, uuid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attr",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(PartnerAddBaseAttr, n_attr),
    PROTOBUF_C_OFFSETOF(PartnerAddBaseAttr, attr),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "power",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerAddBaseAttr, power),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned partner_add_base_attr__field_indices_by_name[] = {
  1,   /* field[1] = attr */
  2,   /* field[2] = power */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange partner_add_base_attr__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor partner_add_base_attr__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PartnerAddBaseAttr",
  "PartnerAddBaseAttr",
  "PartnerAddBaseAttr",
  "",
  sizeof(PartnerAddBaseAttr),
  3,
  partner_add_base_attr__field_descriptors,
  partner_add_base_attr__field_indices_by_name,
  1,  partner_add_base_attr__number_ranges,
  (ProtobufCMessageInit) partner_add_base_attr__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor partner_dismiss_request__field_descriptors[1] =
{
  {
    "uuids",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(PartnerDismissRequest, n_uuids),
    PROTOBUF_C_OFFSETOF(PartnerDismissRequest, uuids),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned partner_dismiss_request__field_indices_by_name[] = {
  0,   /* field[0] = uuids */
};
static const ProtobufCIntRange partner_dismiss_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor partner_dismiss_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PartnerDismissRequest",
  "PartnerDismissRequest",
  "PartnerDismissRequest",
  "",
  sizeof(PartnerDismissRequest),
  1,
  partner_dismiss_request__field_descriptors,
  partner_dismiss_request__field_indices_by_name,
  1,  partner_dismiss_request__number_ranges,
  (ProtobufCMessageInit) partner_dismiss_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor partner_uuid__field_descriptors[1] =
{
  {
    "uuids",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerUuid, uuids),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned partner_uuid__field_indices_by_name[] = {
  0,   /* field[0] = uuids */
};
static const ProtobufCIntRange partner_uuid__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor partner_uuid__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PartnerUuid",
  "PartnerUuid",
  "PartnerUuid",
  "",
  sizeof(PartnerUuid),
  1,
  partner_uuid__field_descriptors,
  partner_uuid__field_indices_by_name,
  1,  partner_uuid__number_ranges,
  (ProtobufCMessageInit) partner_uuid__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor res_reset_attr__field_descriptors[3] =
{
  {
    "ret",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ResResetAttr, ret),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flash_attr",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ResResetAttr, flash_attr),
    &partner_attr__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "power",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ResResetAttr, power),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned res_reset_attr__field_indices_by_name[] = {
  1,   /* field[1] = flash_attr */
  2,   /* field[2] = power */
  0,   /* field[0] = ret */
};
static const ProtobufCIntRange res_reset_attr__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor res_reset_attr__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ResResetAttr",
  "ResResetAttr",
  "ResResetAttr",
  "",
  sizeof(ResResetAttr),
  3,
  res_reset_attr__field_descriptors,
  res_reset_attr__field_indices_by_name,
  1,  res_reset_attr__number_ranges,
  (ProtobufCMessageInit) res_reset_attr__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor strong_partner__field_descriptors[3] =
{
  {
    "uuids",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(StrongPartner, uuids),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attr_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(StrongPartner, attr_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(StrongPartner, count),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned strong_partner__field_indices_by_name[] = {
  1,   /* field[1] = attr_id */
  2,   /* field[2] = count */
  0,   /* field[0] = uuids */
};
static const ProtobufCIntRange strong_partner__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor strong_partner__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "StrongPartner",
  "StrongPartner",
  "StrongPartner",
  "",
  sizeof(StrongPartner),
  3,
  strong_partner__field_descriptors,
  strong_partner__field_indices_by_name,
  1,  strong_partner__number_ranges,
  (ProtobufCMessageInit) strong_partner__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor res_strong_partner__field_descriptors[4] =
{
  {
    "uuids",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ResStrongPartner, uuids),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attr_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ResStrongPartner, attr_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attr_cur",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ResStrongPartner, attr_cur),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ret",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ResStrongPartner, ret),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned res_strong_partner__field_indices_by_name[] = {
  2,   /* field[2] = attr_cur */
  1,   /* field[1] = attr_id */
  3,   /* field[3] = ret */
  0,   /* field[0] = uuids */
};
static const ProtobufCIntRange res_strong_partner__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor res_strong_partner__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ResStrongPartner",
  "ResStrongPartner",
  "ResStrongPartner",
  "",
  sizeof(ResStrongPartner),
  4,
  res_strong_partner__field_descriptors,
  res_strong_partner__field_indices_by_name,
  1,  res_strong_partner__number_ranges,
  (ProtobufCMessageInit) res_strong_partner__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor partner_dismiss_answer__field_descriptors[2] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerDismissAnswer, result),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uuids",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(PartnerDismissAnswer, n_uuids),
    PROTOBUF_C_OFFSETOF(PartnerDismissAnswer, uuids),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned partner_dismiss_answer__field_indices_by_name[] = {
  0,   /* field[0] = result */
  1,   /* field[1] = uuids */
};
static const ProtobufCIntRange partner_dismiss_answer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor partner_dismiss_answer__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PartnerDismissAnswer",
  "PartnerDismissAnswer",
  "PartnerDismissAnswer",
  "",
  sizeof(PartnerDismissAnswer),
  2,
  partner_dismiss_answer__field_descriptors,
  partner_dismiss_answer__field_indices_by_name,
  1,  partner_dismiss_answer__number_ranges,
  (ProtobufCMessageInit) partner_dismiss_answer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor partner_dictionary_add_notify__field_descriptors[1] =
{
  {
    "partnerId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerDictionaryAddNotify, partnerid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned partner_dictionary_add_notify__field_indices_by_name[] = {
  0,   /* field[0] = partnerId */
};
static const ProtobufCIntRange partner_dictionary_add_notify__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor partner_dictionary_add_notify__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PartnerDictionaryAddNotify",
  "PartnerDictionaryAddNotify",
  "PartnerDictionaryAddNotify",
  "",
  sizeof(PartnerDictionaryAddNotify),
  1,
  partner_dictionary_add_notify__field_descriptors,
  partner_dictionary_add_notify__field_indices_by_name,
  1,  partner_dictionary_add_notify__number_ranges,
  (ProtobufCMessageInit) partner_dictionary_add_notify__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor partner_exchange_request__field_descriptors[1] =
{
  {
    "partnerId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerExchangeRequest, partnerid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned partner_exchange_request__field_indices_by_name[] = {
  0,   /* field[0] = partnerId */
};
static const ProtobufCIntRange partner_exchange_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor partner_exchange_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PartnerExchangeRequest",
  "PartnerExchangeRequest",
  "PartnerExchangeRequest",
  "",
  sizeof(PartnerExchangeRequest),
  1,
  partner_exchange_request__field_descriptors,
  partner_exchange_request__field_indices_by_name,
  1,  partner_exchange_request__number_ranges,
  (ProtobufCMessageInit) partner_exchange_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor partner_exchange_answer__field_descriptors[2] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerExchangeAnswer, result),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uuid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerExchangeAnswer, uuid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned partner_exchange_answer__field_indices_by_name[] = {
  0,   /* field[0] = result */
  1,   /* field[1] = uuid */
};
static const ProtobufCIntRange partner_exchange_answer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor partner_exchange_answer__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PartnerExchangeAnswer",
  "PartnerExchangeAnswer",
  "PartnerExchangeAnswer",
  "",
  sizeof(PartnerExchangeAnswer),
  2,
  partner_exchange_answer__field_descriptors,
  partner_exchange_answer__field_indices_by_name,
  1,  partner_exchange_answer__number_ranges,
  (ProtobufCMessageInit) partner_exchange_answer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor partner_recruit_request__field_descriptors[1] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerRecruitRequest, type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned partner_recruit_request__field_indices_by_name[] = {
  0,   /* field[0] = type */
};
static const ProtobufCIntRange partner_recruit_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor partner_recruit_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PartnerRecruitRequest",
  "PartnerRecruitRequest",
  "PartnerRecruitRequest",
  "",
  sizeof(PartnerRecruitRequest),
  1,
  partner_recruit_request__field_descriptors,
  partner_recruit_request__field_indices_by_name,
  1,  partner_recruit_request__number_ranges,
  (ProtobufCMessageInit) partner_recruit_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor partner_recruit_result_data__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerRecruitResultData, type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "item",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerRecruitResultData, item),
    &item_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uuid",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(PartnerRecruitResultData, has_uuid),
    PROTOBUF_C_OFFSETOF(PartnerRecruitResultData, uuid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned partner_recruit_result_data__field_indices_by_name[] = {
  1,   /* field[1] = item */
  0,   /* field[0] = type */
  2,   /* field[2] = uuid */
};
static const ProtobufCIntRange partner_recruit_result_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor partner_recruit_result_data__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PartnerRecruitResultData",
  "PartnerRecruitResultData",
  "PartnerRecruitResultData",
  "",
  sizeof(PartnerRecruitResultData),
  3,
  partner_recruit_result_data__field_descriptors,
  partner_recruit_result_data__field_indices_by_name,
  1,  partner_recruit_result_data__number_ranges,
  (ProtobufCMessageInit) partner_recruit_result_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor partner_recruit_answer__field_descriptors[6] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerRecruitAnswer, result),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "recruits",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(PartnerRecruitAnswer, n_recruits),
    PROTOBUF_C_OFFSETOF(PartnerRecruitAnswer, recruits),
    &partner_recruit_result_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "recruitJuniorTime",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerRecruitAnswer, recruitjuniortime),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "recruitJuniorCount",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerRecruitAnswer, recruitjuniorcount),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "recruitSeniorTime",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerRecruitAnswer, recruitseniortime),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "recruitSeniorCount",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PartnerRecruitAnswer, recruitseniorcount),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned partner_recruit_answer__field_indices_by_name[] = {
  3,   /* field[3] = recruitJuniorCount */
  2,   /* field[2] = recruitJuniorTime */
  5,   /* field[5] = recruitSeniorCount */
  4,   /* field[4] = recruitSeniorTime */
  1,   /* field[1] = recruits */
  0,   /* field[0] = result */
};
static const ProtobufCIntRange partner_recruit_answer__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 5, 2 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor partner_recruit_answer__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PartnerRecruitAnswer",
  "PartnerRecruitAnswer",
  "PartnerRecruitAnswer",
  "",
  sizeof(PartnerRecruitAnswer),
  6,
  partner_recruit_answer__field_descriptors,
  partner_recruit_answer__field_indices_by_name,
  2,  partner_recruit_answer__number_ranges,
  (ProtobufCMessageInit) partner_recruit_answer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
