/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "personality.pb-c.h"
void   personality_data__init
                     (PersonalityData         *message)
{
  static PersonalityData init_value = PERSONALITY_DATA__INIT;
  *message = init_value;
}
size_t personality_data__get_packed_size
                     (const PersonalityData *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &personality_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t personality_data__pack
                     (const PersonalityData *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &personality_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t personality_data__pack_to_buffer
                     (const PersonalityData *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &personality_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PersonalityData *
       personality_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PersonalityData *)
     protobuf_c_message_unpack (&personality_data__descriptor,
                                allocator, len, data);
}
void   personality_data__free_unpacked
                     (PersonalityData *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &personality_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   personality_info_answer__init
                     (PersonalityInfoAnswer         *message)
{
  static PersonalityInfoAnswer init_value = PERSONALITY_INFO_ANSWER__INIT;
  *message = init_value;
}
size_t personality_info_answer__get_packed_size
                     (const PersonalityInfoAnswer *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &personality_info_answer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t personality_info_answer__pack
                     (const PersonalityInfoAnswer *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &personality_info_answer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t personality_info_answer__pack_to_buffer
                     (const PersonalityInfoAnswer *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &personality_info_answer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PersonalityInfoAnswer *
       personality_info_answer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PersonalityInfoAnswer *)
     protobuf_c_message_unpack (&personality_info_answer__descriptor,
                                allocator, len, data);
}
void   personality_info_answer__free_unpacked
                     (PersonalityInfoAnswer *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &personality_info_answer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   personality_set_general_request__init
                     (PersonalitySetGeneralRequest         *message)
{
  static PersonalitySetGeneralRequest init_value = PERSONALITY_SET_GENERAL_REQUEST__INIT;
  *message = init_value;
}
size_t personality_set_general_request__get_packed_size
                     (const PersonalitySetGeneralRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &personality_set_general_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t personality_set_general_request__pack
                     (const PersonalitySetGeneralRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &personality_set_general_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t personality_set_general_request__pack_to_buffer
                     (const PersonalitySetGeneralRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &personality_set_general_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PersonalitySetGeneralRequest *
       personality_set_general_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PersonalitySetGeneralRequest *)
     protobuf_c_message_unpack (&personality_set_general_request__descriptor,
                                allocator, len, data);
}
void   personality_set_general_request__free_unpacked
                     (PersonalitySetGeneralRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &personality_set_general_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   personality_set_tags_request__init
                     (PersonalitySetTagsRequest         *message)
{
  static PersonalitySetTagsRequest init_value = PERSONALITY_SET_TAGS_REQUEST__INIT;
  *message = init_value;
}
size_t personality_set_tags_request__get_packed_size
                     (const PersonalitySetTagsRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &personality_set_tags_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t personality_set_tags_request__pack
                     (const PersonalitySetTagsRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &personality_set_tags_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t personality_set_tags_request__pack_to_buffer
                     (const PersonalitySetTagsRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &personality_set_tags_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PersonalitySetTagsRequest *
       personality_set_tags_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PersonalitySetTagsRequest *)
     protobuf_c_message_unpack (&personality_set_tags_request__descriptor,
                                allocator, len, data);
}
void   personality_set_tags_request__free_unpacked
                     (PersonalitySetTagsRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &personality_set_tags_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   personality_set_intro_request__init
                     (PersonalitySetIntroRequest         *message)
{
  static PersonalitySetIntroRequest init_value = PERSONALITY_SET_INTRO_REQUEST__INIT;
  *message = init_value;
}
size_t personality_set_intro_request__get_packed_size
                     (const PersonalitySetIntroRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &personality_set_intro_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t personality_set_intro_request__pack
                     (const PersonalitySetIntroRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &personality_set_intro_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t personality_set_intro_request__pack_to_buffer
                     (const PersonalitySetIntroRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &personality_set_intro_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PersonalitySetIntroRequest *
       personality_set_intro_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PersonalitySetIntroRequest *)
     protobuf_c_message_unpack (&personality_set_intro_request__descriptor,
                                allocator, len, data);
}
void   personality_set_intro_request__free_unpacked
                     (PersonalitySetIntroRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &personality_set_intro_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   other_detail_data__init
                     (OtherDetailData         *message)
{
  static OtherDetailData init_value = OTHER_DETAIL_DATA__INIT;
  *message = init_value;
}
size_t other_detail_data__get_packed_size
                     (const OtherDetailData *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &other_detail_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t other_detail_data__pack
                     (const OtherDetailData *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &other_detail_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t other_detail_data__pack_to_buffer
                     (const OtherDetailData *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &other_detail_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OtherDetailData *
       other_detail_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OtherDetailData *)
     protobuf_c_message_unpack (&other_detail_data__descriptor,
                                allocator, len, data);
}
void   other_detail_data__free_unpacked
                     (OtherDetailData *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &other_detail_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   get_other_info_request__init
                     (GetOtherInfoRequest         *message)
{
  static GetOtherInfoRequest init_value = GET_OTHER_INFO_REQUEST__INIT;
  *message = init_value;
}
size_t get_other_info_request__get_packed_size
                     (const GetOtherInfoRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &get_other_info_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t get_other_info_request__pack
                     (const GetOtherInfoRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &get_other_info_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t get_other_info_request__pack_to_buffer
                     (const GetOtherInfoRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &get_other_info_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GetOtherInfoRequest *
       get_other_info_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GetOtherInfoRequest *)
     protobuf_c_message_unpack (&get_other_info_request__descriptor,
                                allocator, len, data);
}
void   get_other_info_request__free_unpacked
                     (GetOtherInfoRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &get_other_info_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   get_other_info_answer__init
                     (GetOtherInfoAnswer         *message)
{
  static GetOtherInfoAnswer init_value = GET_OTHER_INFO_ANSWER__INIT;
  *message = init_value;
}
size_t get_other_info_answer__get_packed_size
                     (const GetOtherInfoAnswer *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &get_other_info_answer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t get_other_info_answer__pack
                     (const GetOtherInfoAnswer *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &get_other_info_answer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t get_other_info_answer__pack_to_buffer
                     (const GetOtherInfoAnswer *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &get_other_info_answer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GetOtherInfoAnswer *
       get_other_info_answer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GetOtherInfoAnswer *)
     protobuf_c_message_unpack (&get_other_info_answer__descriptor,
                                allocator, len, data);
}
void   get_other_info_answer__free_unpacked
                     (GetOtherInfoAnswer *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &get_other_info_answer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor personality_data__field_descriptors[6] =
{
  {
    "sex",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PersonalityData, sex),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "birthday",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PersonalityData, birthday),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "location",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PersonalityData, location),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tags",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(PersonalityData, n_tags),
    PROTOBUF_C_OFFSETOF(PersonalityData, tags),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "textIntro",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PersonalityData, textintro),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "voiceIntro",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PersonalityData, voiceintro),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned personality_data__field_indices_by_name[] = {
  1,   /* field[1] = birthday */
  2,   /* field[2] = location */
  0,   /* field[0] = sex */
  3,   /* field[3] = tags */
  4,   /* field[4] = textIntro */
  5,   /* field[5] = voiceIntro */
};
static const ProtobufCIntRange personality_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor personality_data__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PersonalityData",
  "PersonalityData",
  "PersonalityData",
  "",
  sizeof(PersonalityData),
  6,
  personality_data__field_descriptors,
  personality_data__field_indices_by_name,
  1,  personality_data__number_ranges,
  (ProtobufCMessageInit) personality_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor personality_info_answer__field_descriptors[2] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PersonalityInfoAnswer, result),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PersonalityInfoAnswer, data),
    &personality_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned personality_info_answer__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = result */
};
static const ProtobufCIntRange personality_info_answer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor personality_info_answer__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PersonalityInfoAnswer",
  "PersonalityInfoAnswer",
  "PersonalityInfoAnswer",
  "",
  sizeof(PersonalityInfoAnswer),
  2,
  personality_info_answer__field_descriptors,
  personality_info_answer__field_indices_by_name,
  1,  personality_info_answer__number_ranges,
  (ProtobufCMessageInit) personality_info_answer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor personality_set_general_request__field_descriptors[3] =
{
  {
    "sex",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PersonalitySetGeneralRequest, sex),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "birthday",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PersonalitySetGeneralRequest, birthday),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "location",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PersonalitySetGeneralRequest, location),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned personality_set_general_request__field_indices_by_name[] = {
  1,   /* field[1] = birthday */
  2,   /* field[2] = location */
  0,   /* field[0] = sex */
};
static const ProtobufCIntRange personality_set_general_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor personality_set_general_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PersonalitySetGeneralRequest",
  "PersonalitySetGeneralRequest",
  "PersonalitySetGeneralRequest",
  "",
  sizeof(PersonalitySetGeneralRequest),
  3,
  personality_set_general_request__field_descriptors,
  personality_set_general_request__field_indices_by_name,
  1,  personality_set_general_request__number_ranges,
  (ProtobufCMessageInit) personality_set_general_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor personality_set_tags_request__field_descriptors[1] =
{
  {
    "tags",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(PersonalitySetTagsRequest, n_tags),
    PROTOBUF_C_OFFSETOF(PersonalitySetTagsRequest, tags),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned personality_set_tags_request__field_indices_by_name[] = {
  0,   /* field[0] = tags */
};
static const ProtobufCIntRange personality_set_tags_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor personality_set_tags_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PersonalitySetTagsRequest",
  "PersonalitySetTagsRequest",
  "PersonalitySetTagsRequest",
  "",
  sizeof(PersonalitySetTagsRequest),
  1,
  personality_set_tags_request__field_descriptors,
  personality_set_tags_request__field_indices_by_name,
  1,  personality_set_tags_request__number_ranges,
  (ProtobufCMessageInit) personality_set_tags_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor personality_set_intro_request__field_descriptors[2] =
{
  {
    "textIntro",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PersonalitySetIntroRequest, textintro),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "voiceIntro",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PersonalitySetIntroRequest, voiceintro),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned personality_set_intro_request__field_indices_by_name[] = {
  0,   /* field[0] = textIntro */
  1,   /* field[1] = voiceIntro */
};
static const ProtobufCIntRange personality_set_intro_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor personality_set_intro_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PersonalitySetIntroRequest",
  "PersonalitySetIntroRequest",
  "PersonalitySetIntroRequest",
  "",
  sizeof(PersonalitySetIntroRequest),
  2,
  personality_set_intro_request__field_descriptors,
  personality_set_intro_request__field_indices_by_name,
  1,  personality_set_intro_request__number_ranges,
  (ProtobufCMessageInit) personality_set_intro_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor other_detail_data__field_descriptors[11] =
{
  {
    "playerId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OtherDetailData, playerid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OtherDetailData, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attrs",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(OtherDetailData, n_attrs),
    PROTOBUF_C_OFFSETOF(OtherDetailData, attrs),
    &attr_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "guildId",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OtherDetailData, guildid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "guildName",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OtherDetailData, guildname),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "guildOffice",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OtherDetailData, guildoffice),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "campTitle",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OtherDetailData, camptitle),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "personality",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OtherDetailData, personality),
    &personality_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "equips",
    12,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(OtherDetailData, n_equips),
    PROTOBUF_C_OFFSETOF(OtherDetailData, equips),
    &equip_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "baguas",
    13,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(OtherDetailData, n_baguas),
    PROTOBUF_C_OFFSETOF(OtherDetailData, baguas),
    &baguapai_dress_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "teamId",
    14,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OtherDetailData, teamid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned other_detail_data__field_indices_by_name[] = {
  2,   /* field[2] = attrs */
  9,   /* field[9] = baguas */
  6,   /* field[6] = campTitle */
  8,   /* field[8] = equips */
  3,   /* field[3] = guildId */
  4,   /* field[4] = guildName */
  5,   /* field[5] = guildOffice */
  1,   /* field[1] = name */
  7,   /* field[7] = personality */
  0,   /* field[0] = playerId */
  10,   /* field[10] = teamId */
};
static const ProtobufCIntRange other_detail_data__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 6, 3 },
  { 10, 6 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor other_detail_data__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "OtherDetailData",
  "OtherDetailData",
  "OtherDetailData",
  "",
  sizeof(OtherDetailData),
  11,
  other_detail_data__field_descriptors,
  other_detail_data__field_indices_by_name,
  3,  other_detail_data__number_ranges,
  (ProtobufCMessageInit) other_detail_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor get_other_info_request__field_descriptors[1] =
{
  {
    "playerId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GetOtherInfoRequest, playerid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned get_other_info_request__field_indices_by_name[] = {
  0,   /* field[0] = playerId */
};
static const ProtobufCIntRange get_other_info_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor get_other_info_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "GetOtherInfoRequest",
  "GetOtherInfoRequest",
  "GetOtherInfoRequest",
  "",
  sizeof(GetOtherInfoRequest),
  1,
  get_other_info_request__field_descriptors,
  get_other_info_request__field_indices_by_name,
  1,  get_other_info_request__number_ranges,
  (ProtobufCMessageInit) get_other_info_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor get_other_info_answer__field_descriptors[2] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GetOtherInfoAnswer, result),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GetOtherInfoAnswer, data),
    &other_detail_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned get_other_info_answer__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = result */
};
static const ProtobufCIntRange get_other_info_answer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor get_other_info_answer__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "GetOtherInfoAnswer",
  "GetOtherInfoAnswer",
  "GetOtherInfoAnswer",
  "",
  sizeof(GetOtherInfoAnswer),
  2,
  get_other_info_answer__field_descriptors,
  get_other_info_answer__field_indices_by_name,
  1,  get_other_info_answer__number_ranges,
  (ProtobufCMessageInit) get_other_info_answer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
