/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "pk.pb-c.h"
void   set_pk_type_request__init
                     (SetPkTypeRequest         *message)
{
  static SetPkTypeRequest init_value = SET_PK_TYPE_REQUEST__INIT;
  *message = init_value;
}
size_t set_pk_type_request__get_packed_size
                     (const SetPkTypeRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &set_pk_type_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t set_pk_type_request__pack
                     (const SetPkTypeRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &set_pk_type_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t set_pk_type_request__pack_to_buffer
                     (const SetPkTypeRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &set_pk_type_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SetPkTypeRequest *
       set_pk_type_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SetPkTypeRequest *)
     protobuf_c_message_unpack (&set_pk_type_request__descriptor,
                                allocator, len, data);
}
void   set_pk_type_request__free_unpacked
                     (SetPkTypeRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &set_pk_type_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   set_pk_type_answer__init
                     (SetPkTypeAnswer         *message)
{
  static SetPkTypeAnswer init_value = SET_PK_TYPE_ANSWER__INIT;
  *message = init_value;
}
size_t set_pk_type_answer__get_packed_size
                     (const SetPkTypeAnswer *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &set_pk_type_answer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t set_pk_type_answer__pack
                     (const SetPkTypeAnswer *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &set_pk_type_answer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t set_pk_type_answer__pack_to_buffer
                     (const SetPkTypeAnswer *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &set_pk_type_answer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SetPkTypeAnswer *
       set_pk_type_answer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SetPkTypeAnswer *)
     protobuf_c_message_unpack (&set_pk_type_answer__descriptor,
                                allocator, len, data);
}
void   set_pk_type_answer__free_unpacked
                     (SetPkTypeAnswer *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &set_pk_type_answer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   qiecuo_request__init
                     (QiecuoRequest         *message)
{
  static QiecuoRequest init_value = QIECUO_REQUEST__INIT;
  *message = init_value;
}
size_t qiecuo_request__get_packed_size
                     (const QiecuoRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &qiecuo_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t qiecuo_request__pack
                     (const QiecuoRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &qiecuo_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t qiecuo_request__pack_to_buffer
                     (const QiecuoRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &qiecuo_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
QiecuoRequest *
       qiecuo_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (QiecuoRequest *)
     protobuf_c_message_unpack (&qiecuo_request__descriptor,
                                allocator, len, data);
}
void   qiecuo_request__free_unpacked
                     (QiecuoRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &qiecuo_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   qiecuo_notify__init
                     (QiecuoNotify         *message)
{
  static QiecuoNotify init_value = QIECUO_NOTIFY__INIT;
  *message = init_value;
}
size_t qiecuo_notify__get_packed_size
                     (const QiecuoNotify *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &qiecuo_notify__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t qiecuo_notify__pack
                     (const QiecuoNotify *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &qiecuo_notify__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t qiecuo_notify__pack_to_buffer
                     (const QiecuoNotify *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &qiecuo_notify__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
QiecuoNotify *
       qiecuo_notify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (QiecuoNotify *)
     protobuf_c_message_unpack (&qiecuo_notify__descriptor,
                                allocator, len, data);
}
void   qiecuo_notify__free_unpacked
                     (QiecuoNotify *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &qiecuo_notify__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   qiecuo_start_request__init
                     (QiecuoStartRequest         *message)
{
  static QiecuoStartRequest init_value = QIECUO_START_REQUEST__INIT;
  *message = init_value;
}
size_t qiecuo_start_request__get_packed_size
                     (const QiecuoStartRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &qiecuo_start_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t qiecuo_start_request__pack
                     (const QiecuoStartRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &qiecuo_start_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t qiecuo_start_request__pack_to_buffer
                     (const QiecuoStartRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &qiecuo_start_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
QiecuoStartRequest *
       qiecuo_start_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (QiecuoStartRequest *)
     protobuf_c_message_unpack (&qiecuo_start_request__descriptor,
                                allocator, len, data);
}
void   qiecuo_start_request__free_unpacked
                     (QiecuoStartRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &qiecuo_start_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   qiecuo_start_notify__init
                     (QiecuoStartNotify         *message)
{
  static QiecuoStartNotify init_value = QIECUO_START_NOTIFY__INIT;
  *message = init_value;
}
size_t qiecuo_start_notify__get_packed_size
                     (const QiecuoStartNotify *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &qiecuo_start_notify__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t qiecuo_start_notify__pack
                     (const QiecuoStartNotify *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &qiecuo_start_notify__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t qiecuo_start_notify__pack_to_buffer
                     (const QiecuoStartNotify *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &qiecuo_start_notify__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
QiecuoStartNotify *
       qiecuo_start_notify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (QiecuoStartNotify *)
     protobuf_c_message_unpack (&qiecuo_start_notify__descriptor,
                                allocator, len, data);
}
void   qiecuo_start_notify__free_unpacked
                     (QiecuoStartNotify *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &qiecuo_start_notify__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   qiecuo_finish_notify__init
                     (QiecuoFinishNotify         *message)
{
  static QiecuoFinishNotify init_value = QIECUO_FINISH_NOTIFY__INIT;
  *message = init_value;
}
size_t qiecuo_finish_notify__get_packed_size
                     (const QiecuoFinishNotify *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &qiecuo_finish_notify__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t qiecuo_finish_notify__pack
                     (const QiecuoFinishNotify *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &qiecuo_finish_notify__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t qiecuo_finish_notify__pack_to_buffer
                     (const QiecuoFinishNotify *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &qiecuo_finish_notify__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
QiecuoFinishNotify *
       qiecuo_finish_notify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (QiecuoFinishNotify *)
     protobuf_c_message_unpack (&qiecuo_finish_notify__descriptor,
                                allocator, len, data);
}
void   qiecuo_finish_notify__free_unpacked
                     (QiecuoFinishNotify *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &qiecuo_finish_notify__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   qiecuo_refuse_request__init
                     (QiecuoRefuseRequest         *message)
{
  static QiecuoRefuseRequest init_value = QIECUO_REFUSE_REQUEST__INIT;
  *message = init_value;
}
size_t qiecuo_refuse_request__get_packed_size
                     (const QiecuoRefuseRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &qiecuo_refuse_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t qiecuo_refuse_request__pack
                     (const QiecuoRefuseRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &qiecuo_refuse_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t qiecuo_refuse_request__pack_to_buffer
                     (const QiecuoRefuseRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &qiecuo_refuse_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
QiecuoRefuseRequest *
       qiecuo_refuse_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (QiecuoRefuseRequest *)
     protobuf_c_message_unpack (&qiecuo_refuse_request__descriptor,
                                allocator, len, data);
}
void   qiecuo_refuse_request__free_unpacked
                     (QiecuoRefuseRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &qiecuo_refuse_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   qiecuo_refuse_notify__init
                     (QiecuoRefuseNotify         *message)
{
  static QiecuoRefuseNotify init_value = QIECUO_REFUSE_NOTIFY__INIT;
  *message = init_value;
}
size_t qiecuo_refuse_notify__get_packed_size
                     (const QiecuoRefuseNotify *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &qiecuo_refuse_notify__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t qiecuo_refuse_notify__pack
                     (const QiecuoRefuseNotify *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &qiecuo_refuse_notify__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t qiecuo_refuse_notify__pack_to_buffer
                     (const QiecuoRefuseNotify *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &qiecuo_refuse_notify__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
QiecuoRefuseNotify *
       qiecuo_refuse_notify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (QiecuoRefuseNotify *)
     protobuf_c_message_unpack (&qiecuo_refuse_notify__descriptor,
                                allocator, len, data);
}
void   qiecuo_refuse_notify__free_unpacked
                     (QiecuoRefuseNotify *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &qiecuo_refuse_notify__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor set_pk_type_request__field_descriptors[1] =
{
  {
    "pk_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SetPkTypeRequest, pk_type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned set_pk_type_request__field_indices_by_name[] = {
  0,   /* field[0] = pk_type */
};
static const ProtobufCIntRange set_pk_type_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor set_pk_type_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "set_pk_type_request",
  "SetPkTypeRequest",
  "SetPkTypeRequest",
  "",
  sizeof(SetPkTypeRequest),
  1,
  set_pk_type_request__field_descriptors,
  set_pk_type_request__field_indices_by_name,
  1,  set_pk_type_request__number_ranges,
  (ProtobufCMessageInit) set_pk_type_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor set_pk_type_answer__field_descriptors[2] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SetPkTypeAnswer, result),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pk_type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SetPkTypeAnswer, pk_type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned set_pk_type_answer__field_indices_by_name[] = {
  1,   /* field[1] = pk_type */
  0,   /* field[0] = result */
};
static const ProtobufCIntRange set_pk_type_answer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor set_pk_type_answer__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "set_pk_type_answer",
  "SetPkTypeAnswer",
  "SetPkTypeAnswer",
  "",
  sizeof(SetPkTypeAnswer),
  2,
  set_pk_type_answer__field_descriptors,
  set_pk_type_answer__field_indices_by_name,
  1,  set_pk_type_answer__number_ranges,
  (ProtobufCMessageInit) set_pk_type_answer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor qiecuo_request__field_descriptors[1] =
{
  {
    "player_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(QiecuoRequest, player_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned qiecuo_request__field_indices_by_name[] = {
  0,   /* field[0] = player_id */
};
static const ProtobufCIntRange qiecuo_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor qiecuo_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "qiecuo_request",
  "QiecuoRequest",
  "QiecuoRequest",
  "",
  sizeof(QiecuoRequest),
  1,
  qiecuo_request__field_descriptors,
  qiecuo_request__field_indices_by_name,
  1,  qiecuo_request__number_ranges,
  (ProtobufCMessageInit) qiecuo_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor qiecuo_notify__field_descriptors[2] =
{
  {
    "player_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(QiecuoNotify, player_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(QiecuoNotify, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned qiecuo_notify__field_indices_by_name[] = {
  1,   /* field[1] = name */
  0,   /* field[0] = player_id */
};
static const ProtobufCIntRange qiecuo_notify__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor qiecuo_notify__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "qiecuo_notify",
  "QiecuoNotify",
  "QiecuoNotify",
  "",
  sizeof(QiecuoNotify),
  2,
  qiecuo_notify__field_descriptors,
  qiecuo_notify__field_indices_by_name,
  1,  qiecuo_notify__number_ranges,
  (ProtobufCMessageInit) qiecuo_notify__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor qiecuo_start_request__field_descriptors[1] =
{
  {
    "player_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(QiecuoStartRequest, player_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned qiecuo_start_request__field_indices_by_name[] = {
  0,   /* field[0] = player_id */
};
static const ProtobufCIntRange qiecuo_start_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor qiecuo_start_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "qiecuo_start_request",
  "QiecuoStartRequest",
  "QiecuoStartRequest",
  "",
  sizeof(QiecuoStartRequest),
  1,
  qiecuo_start_request__field_descriptors,
  qiecuo_start_request__field_indices_by_name,
  1,  qiecuo_start_request__number_ranges,
  (ProtobufCMessageInit) qiecuo_start_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor qiecuo_start_notify__field_descriptors[4] =
{
  {
    "pos_x",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(QiecuoStartNotify, pos_x),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_z",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(QiecuoStartNotify, pos_z),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "player_id",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(QiecuoStartNotify, player_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(QiecuoStartNotify, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned qiecuo_start_notify__field_indices_by_name[] = {
  3,   /* field[3] = name */
  2,   /* field[2] = player_id */
  0,   /* field[0] = pos_x */
  1,   /* field[1] = pos_z */
};
static const ProtobufCIntRange qiecuo_start_notify__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor qiecuo_start_notify__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "qiecuo_start_notify",
  "QiecuoStartNotify",
  "QiecuoStartNotify",
  "",
  sizeof(QiecuoStartNotify),
  4,
  qiecuo_start_notify__field_descriptors,
  qiecuo_start_notify__field_indices_by_name,
  1,  qiecuo_start_notify__number_ranges,
  (ProtobufCMessageInit) qiecuo_start_notify__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor qiecuo_finish_notify__field_descriptors[1] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(QiecuoFinishNotify, result),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned qiecuo_finish_notify__field_indices_by_name[] = {
  0,   /* field[0] = result */
};
static const ProtobufCIntRange qiecuo_finish_notify__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor qiecuo_finish_notify__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "qiecuo_finish_notify",
  "QiecuoFinishNotify",
  "QiecuoFinishNotify",
  "",
  sizeof(QiecuoFinishNotify),
  1,
  qiecuo_finish_notify__field_descriptors,
  qiecuo_finish_notify__field_indices_by_name,
  1,  qiecuo_finish_notify__number_ranges,
  (ProtobufCMessageInit) qiecuo_finish_notify__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor qiecuo_refuse_request__field_descriptors[1] =
{
  {
    "player_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(QiecuoRefuseRequest, player_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned qiecuo_refuse_request__field_indices_by_name[] = {
  0,   /* field[0] = player_id */
};
static const ProtobufCIntRange qiecuo_refuse_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor qiecuo_refuse_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "qiecuo_refuse_request",
  "QiecuoRefuseRequest",
  "QiecuoRefuseRequest",
  "",
  sizeof(QiecuoRefuseRequest),
  1,
  qiecuo_refuse_request__field_descriptors,
  qiecuo_refuse_request__field_indices_by_name,
  1,  qiecuo_refuse_request__number_ranges,
  (ProtobufCMessageInit) qiecuo_refuse_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor qiecuo_refuse_notify__field_descriptors[2] =
{
  {
    "player_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(QiecuoRefuseNotify, player_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(QiecuoRefuseNotify, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned qiecuo_refuse_notify__field_indices_by_name[] = {
  1,   /* field[1] = name */
  0,   /* field[0] = player_id */
};
static const ProtobufCIntRange qiecuo_refuse_notify__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor qiecuo_refuse_notify__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "qiecuo_refuse_notify",
  "QiecuoRefuseNotify",
  "QiecuoRefuseNotify",
  "",
  sizeof(QiecuoRefuseNotify),
  2,
  qiecuo_refuse_notify__field_descriptors,
  qiecuo_refuse_notify__field_indices_by_name,
  1,  qiecuo_refuse_notify__number_ranges,
  (ProtobufCMessageInit) qiecuo_refuse_notify__init,
  NULL,NULL,NULL    /* reserved[123] */
};
