/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "rank.pb-c.h"
void   rank_player_data__init
                     (RankPlayerData         *message)
{
  static RankPlayerData init_value = RANK_PLAYER_DATA__INIT;
  *message = init_value;
}
size_t rank_player_data__get_packed_size
                     (const RankPlayerData *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rank_player_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rank_player_data__pack
                     (const RankPlayerData *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rank_player_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rank_player_data__pack_to_buffer
                     (const RankPlayerData *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rank_player_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RankPlayerData *
       rank_player_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RankPlayerData *)
     protobuf_c_message_unpack (&rank_player_data__descriptor,
                                allocator, len, data);
}
void   rank_player_data__free_unpacked
                     (RankPlayerData *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rank_player_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rank_info_request__init
                     (RankInfoRequest         *message)
{
  static RankInfoRequest init_value = RANK_INFO_REQUEST__INIT;
  *message = init_value;
}
size_t rank_info_request__get_packed_size
                     (const RankInfoRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rank_info_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rank_info_request__pack
                     (const RankInfoRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rank_info_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rank_info_request__pack_to_buffer
                     (const RankInfoRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rank_info_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RankInfoRequest *
       rank_info_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RankInfoRequest *)
     protobuf_c_message_unpack (&rank_info_request__descriptor,
                                allocator, len, data);
}
void   rank_info_request__free_unpacked
                     (RankInfoRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rank_info_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rank_info_answer__init
                     (RankInfoAnswer         *message)
{
  static RankInfoAnswer init_value = RANK_INFO_ANSWER__INIT;
  *message = init_value;
}
size_t rank_info_answer__get_packed_size
                     (const RankInfoAnswer *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rank_info_answer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rank_info_answer__pack
                     (const RankInfoAnswer *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rank_info_answer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rank_info_answer__pack_to_buffer
                     (const RankInfoAnswer *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rank_info_answer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RankInfoAnswer *
       rank_info_answer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RankInfoAnswer *)
     protobuf_c_message_unpack (&rank_info_answer__descriptor,
                                allocator, len, data);
}
void   rank_info_answer__free_unpacked
                     (RankInfoAnswer *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rank_info_answer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor rank_player_data__field_descriptors[5] =
{
  {
    "baseInfo",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RankPlayerData, baseinfo),
    &player_base_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "guildId",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RankPlayerData, guildid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "guildName",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RankPlayerData, guildname),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rankNum",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RankPlayerData, ranknum),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "score",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RankPlayerData, score),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rank_player_data__field_indices_by_name[] = {
  0,   /* field[0] = baseInfo */
  1,   /* field[1] = guildId */
  2,   /* field[2] = guildName */
  3,   /* field[3] = rankNum */
  4,   /* field[4] = score */
};
static const ProtobufCIntRange rank_player_data__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 4, 1 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor rank_player_data__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RankPlayerData",
  "RankPlayerData",
  "RankPlayerData",
  "",
  sizeof(RankPlayerData),
  5,
  rank_player_data__field_descriptors,
  rank_player_data__field_indices_by_name,
  2,  rank_player_data__number_ranges,
  (ProtobufCMessageInit) rank_player_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rank_info_request__field_descriptors[1] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RankInfoRequest, type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rank_info_request__field_indices_by_name[] = {
  0,   /* field[0] = type */
};
static const ProtobufCIntRange rank_info_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rank_info_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RankInfoRequest",
  "RankInfoRequest",
  "RankInfoRequest",
  "",
  sizeof(RankInfoRequest),
  1,
  rank_info_request__field_descriptors,
  rank_info_request__field_indices_by_name,
  1,  rank_info_request__number_ranges,
  (ProtobufCMessageInit) rank_info_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rank_info_answer__field_descriptors[3] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RankInfoAnswer, result),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "infos",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(RankInfoAnswer, n_infos),
    PROTOBUF_C_OFFSETOF(RankInfoAnswer, infos),
    &rank_player_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "myRank",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RankInfoAnswer, myrank),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rank_info_answer__field_indices_by_name[] = {
  1,   /* field[1] = infos */
  2,   /* field[2] = myRank */
  0,   /* field[0] = result */
};
static const ProtobufCIntRange rank_info_answer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor rank_info_answer__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RankInfoAnswer",
  "RankInfoAnswer",
  "RankInfoAnswer",
  "",
  sizeof(RankInfoAnswer),
  3,
  rank_info_answer__field_descriptors,
  rank_info_answer__field_indices_by_name,
  1,  rank_info_answer__number_ranges,
  (ProtobufCMessageInit) rank_info_answer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue rank_type__enum_values_by_number[27] =
{
  { "RANK_LEVEL_TOTAL", "RANK_TYPE__RANK_LEVEL_TOTAL", 11 },
  { "RANK_LEVEL_JOB1", "RANK_TYPE__RANK_LEVEL_JOB1", 12 },
  { "RANK_LEVEL_JOB2", "RANK_TYPE__RANK_LEVEL_JOB2", 13 },
  { "RANK_LEVEL_JOB3", "RANK_TYPE__RANK_LEVEL_JOB3", 14 },
  { "RANK_LEVEL_JOB4", "RANK_TYPE__RANK_LEVEL_JOB4", 15 },
  { "RANK_LEVEL_JOB5", "RANK_TYPE__RANK_LEVEL_JOB5", 16 },
  { "RANK_FC_TOTAL", "RANK_TYPE__RANK_FC_TOTAL", 21 },
  { "RANK_FC_JOB1", "RANK_TYPE__RANK_FC_JOB1", 22 },
  { "RANK_FC_JOB2", "RANK_TYPE__RANK_FC_JOB2", 23 },
  { "RANK_FC_JOB3", "RANK_TYPE__RANK_FC_JOB3", 24 },
  { "RANK_FC_JOB4", "RANK_TYPE__RANK_FC_JOB4", 25 },
  { "RANK_FC_JOB5", "RANK_TYPE__RANK_FC_JOB5", 26 },
  { "RANK_EQUIP_TOTAL", "RANK_TYPE__RANK_EQUIP_TOTAL", 31 },
  { "RANK_EQUIP_JOB1", "RANK_TYPE__RANK_EQUIP_JOB1", 32 },
  { "RANK_EQUIP_JOB2", "RANK_TYPE__RANK_EQUIP_JOB2", 33 },
  { "RANK_EQUIP_JOB3", "RANK_TYPE__RANK_EQUIP_JOB3", 34 },
  { "RANK_EQUIP_JOB4", "RANK_TYPE__RANK_EQUIP_JOB4", 35 },
  { "RANK_EQUIP_JOB5", "RANK_TYPE__RANK_EQUIP_JOB5", 36 },
  { "RANK_TREASURE_COIN", "RANK_TYPE__RANK_TREASURE_COIN", 47 },
  { "RANK_TREASURE_GOLD", "RANK_TYPE__RANK_TREASURE_GOLD", 48 },
  { "RANK_TREASURE_BIND_GOLD", "RANK_TYPE__RANK_TREASURE_BIND_GOLD", 49 },
  { "RANK_BAGUA_TOTAL", "RANK_TYPE__RANK_BAGUA_TOTAL", 51 },
  { "RANK_BAGUA_JOB1", "RANK_TYPE__RANK_BAGUA_JOB1", 52 },
  { "RANK_BAGUA_JOB2", "RANK_TYPE__RANK_BAGUA_JOB2", 53 },
  { "RANK_BAGUA_JOB3", "RANK_TYPE__RANK_BAGUA_JOB3", 54 },
  { "RANK_BAGUA_JOB4", "RANK_TYPE__RANK_BAGUA_JOB4", 55 },
  { "RANK_BAGUA_JOB5", "RANK_TYPE__RANK_BAGUA_JOB5", 56 },
};
static const ProtobufCIntRange rank_type__value_ranges[] = {
{11, 0},{21, 6},{31, 12},{47, 18},{51, 21},{0, 27}
};
const ProtobufCEnumValueIndex rank_type__enum_values_by_name[27] =
{
  { "RANK_BAGUA_JOB1", 22 },
  { "RANK_BAGUA_JOB2", 23 },
  { "RANK_BAGUA_JOB3", 24 },
  { "RANK_BAGUA_JOB4", 25 },
  { "RANK_BAGUA_JOB5", 26 },
  { "RANK_BAGUA_TOTAL", 21 },
  { "RANK_EQUIP_JOB1", 13 },
  { "RANK_EQUIP_JOB2", 14 },
  { "RANK_EQUIP_JOB3", 15 },
  { "RANK_EQUIP_JOB4", 16 },
  { "RANK_EQUIP_JOB5", 17 },
  { "RANK_EQUIP_TOTAL", 12 },
  { "RANK_FC_JOB1", 7 },
  { "RANK_FC_JOB2", 8 },
  { "RANK_FC_JOB3", 9 },
  { "RANK_FC_JOB4", 10 },
  { "RANK_FC_JOB5", 11 },
  { "RANK_FC_TOTAL", 6 },
  { "RANK_LEVEL_JOB1", 1 },
  { "RANK_LEVEL_JOB2", 2 },
  { "RANK_LEVEL_JOB3", 3 },
  { "RANK_LEVEL_JOB4", 4 },
  { "RANK_LEVEL_JOB5", 5 },
  { "RANK_LEVEL_TOTAL", 0 },
  { "RANK_TREASURE_BIND_GOLD", 20 },
  { "RANK_TREASURE_COIN", 18 },
  { "RANK_TREASURE_GOLD", 19 },
};
const ProtobufCEnumDescriptor rank_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "RankType",
  "RankType",
  "RankType",
  "",
  27,
  rank_type__enum_values_by_number,
  27,
  rank_type__enum_values_by_name,
  5,
  rank_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
