/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "scene_transfer.pb-c.h"
void   scene_transfer_request__init
                     (SceneTransferRequest         *message)
{
  static SceneTransferRequest init_value = SCENE_TRANSFER_REQUEST__INIT;
  *message = init_value;
}
size_t scene_transfer_request__get_packed_size
                     (const SceneTransferRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scene_transfer_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scene_transfer_request__pack
                     (const SceneTransferRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scene_transfer_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scene_transfer_request__pack_to_buffer
                     (const SceneTransferRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scene_transfer_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SceneTransferRequest *
       scene_transfer_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SceneTransferRequest *)
     protobuf_c_message_unpack (&scene_transfer_request__descriptor,
                                allocator, len, data);
}
void   scene_transfer_request__free_unpacked
                     (SceneTransferRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scene_transfer_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   scene_transfer_answer__init
                     (SceneTransferAnswer         *message)
{
  static SceneTransferAnswer init_value = SCENE_TRANSFER_ANSWER__INIT;
  *message = init_value;
}
size_t scene_transfer_answer__get_packed_size
                     (const SceneTransferAnswer *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scene_transfer_answer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scene_transfer_answer__pack
                     (const SceneTransferAnswer *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scene_transfer_answer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scene_transfer_answer__pack_to_buffer
                     (const SceneTransferAnswer *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scene_transfer_answer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SceneTransferAnswer *
       scene_transfer_answer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SceneTransferAnswer *)
     protobuf_c_message_unpack (&scene_transfer_answer__descriptor,
                                allocator, len, data);
}
void   scene_transfer_answer__free_unpacked
                     (SceneTransferAnswer *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scene_transfer_answer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   transfer_to_player_scene_request__init
                     (TransferToPlayerSceneRequest         *message)
{
  static TransferToPlayerSceneRequest init_value = TRANSFER_TO_PLAYER_SCENE_REQUEST__INIT;
  *message = init_value;
}
size_t transfer_to_player_scene_request__get_packed_size
                     (const TransferToPlayerSceneRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transfer_to_player_scene_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t transfer_to_player_scene_request__pack
                     (const TransferToPlayerSceneRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transfer_to_player_scene_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t transfer_to_player_scene_request__pack_to_buffer
                     (const TransferToPlayerSceneRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transfer_to_player_scene_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TransferToPlayerSceneRequest *
       transfer_to_player_scene_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TransferToPlayerSceneRequest *)
     protobuf_c_message_unpack (&transfer_to_player_scene_request__descriptor,
                                allocator, len, data);
}
void   transfer_to_player_scene_request__free_unpacked
                     (TransferToPlayerSceneRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transfer_to_player_scene_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor scene_transfer_request__field_descriptors[2] =
{
  {
    "transfer_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SceneTransferRequest, transfer_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SceneTransferRequest, type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scene_transfer_request__field_indices_by_name[] = {
  0,   /* field[0] = transfer_id */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange scene_transfer_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor scene_transfer_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "scene_transfer_request",
  "SceneTransferRequest",
  "SceneTransferRequest",
  "",
  sizeof(SceneTransferRequest),
  2,
  scene_transfer_request__field_descriptors,
  scene_transfer_request__field_indices_by_name,
  1,  scene_transfer_request__number_ranges,
  (ProtobufCMessageInit) scene_transfer_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor scene_transfer_answer__field_descriptors[6] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SceneTransferAnswer, result),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "new_scene_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SceneTransferAnswer, new_scene_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_x",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SceneTransferAnswer, pos_x),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_z",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SceneTransferAnswer, pos_z),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "direct",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SceneTransferAnswer, direct),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_y",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SceneTransferAnswer, pos_y),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scene_transfer_answer__field_indices_by_name[] = {
  4,   /* field[4] = direct */
  1,   /* field[1] = new_scene_id */
  2,   /* field[2] = pos_x */
  5,   /* field[5] = pos_y */
  3,   /* field[3] = pos_z */
  0,   /* field[0] = result */
};
static const ProtobufCIntRange scene_transfer_answer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor scene_transfer_answer__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "scene_transfer_answer",
  "SceneTransferAnswer",
  "SceneTransferAnswer",
  "",
  sizeof(SceneTransferAnswer),
  6,
  scene_transfer_answer__field_descriptors,
  scene_transfer_answer__field_indices_by_name,
  1,  scene_transfer_answer__number_ranges,
  (ProtobufCMessageInit) scene_transfer_answer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor transfer_to_player_scene_request__field_descriptors[1] =
{
  {
    "player_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransferToPlayerSceneRequest, player_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned transfer_to_player_scene_request__field_indices_by_name[] = {
  0,   /* field[0] = player_id */
};
static const ProtobufCIntRange transfer_to_player_scene_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor transfer_to_player_scene_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "transfer_to_player_scene_request",
  "TransferToPlayerSceneRequest",
  "TransferToPlayerSceneRequest",
  "",
  sizeof(TransferToPlayerSceneRequest),
  1,
  transfer_to_player_scene_request__field_descriptors,
  transfer_to_player_scene_request__field_indices_by_name,
  1,  transfer_to_player_scene_request__number_ranges,
  (ProtobufCMessageInit) transfer_to_player_scene_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
