/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_xunbao_2eproto__INCLUDED
#define PROTOBUF_C_xunbao_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _XunbaoPos XunbaoPos;
typedef struct _CashTruckInfo CashTruckInfo;
typedef struct _AcceptCashTruck AcceptCashTruck;
typedef struct _UpDownCashTruck UpDownCashTruck;
typedef struct _ResAcceptCashTruck ResAcceptCashTruck;
typedef struct _TruckEndurance TruckEndurance;


/* --- enums --- */


/* --- messages --- */

struct  _XunbaoPos
{
  ProtobufCMessage base;
  uint32_t mapid;
  uint32_t x;
  uint32_t z;
  uint32_t transfer;
};
#define XUNBAO_POS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&xunbao_pos__descriptor) \
    , 0, 0, 0, 0 }


struct  _CashTruckInfo
{
  ProtobufCMessage base;
  uint32_t num_cion;
  uint32_t num_gold;
  uint64_t cash_truck;
  uint32_t mapid;
  uint32_t x;
  uint32_t z;
};
#define CASH_TRUCK_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cash_truck_info__descriptor) \
    , 0, 0, 0, 0, 0, 0 }


struct  _AcceptCashTruck
{
  ProtobufCMessage base;
  uint32_t id;
};
#define ACCEPT_CASH_TRUCK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&accept_cash_truck__descriptor) \
    , 0 }


struct  _UpDownCashTruck
{
  ProtobufCMessage base;
  uint64_t cash_truck;
  uint64_t playerid;
};
#define UP_DOWN_CASH_TRUCK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&up_down_cash_truck__descriptor) \
    , 0, 0 }


struct  _ResAcceptCashTruck
{
  ProtobufCMessage base;
  uint32_t id;
  uint32_t ret;
};
#define RES_ACCEPT_CASH_TRUCK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&res_accept_cash_truck__descriptor) \
    , 0, 0 }


struct  _TruckEndurance
{
  ProtobufCMessage base;
  uint32_t endurance;
};
#define TRUCK_ENDURANCE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&truck_endurance__descriptor) \
    , 0 }


/* XunbaoPos methods */
void   xunbao_pos__init
                     (XunbaoPos         *message);
size_t xunbao_pos__get_packed_size
                     (const XunbaoPos   *message);
size_t xunbao_pos__pack
                     (const XunbaoPos   *message,
                      uint8_t             *out);
size_t xunbao_pos__pack_to_buffer
                     (const XunbaoPos   *message,
                      ProtobufCBuffer     *buffer);
XunbaoPos *
       xunbao_pos__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   xunbao_pos__free_unpacked
                     (XunbaoPos *message,
                      ProtobufCAllocator *allocator);
/* CashTruckInfo methods */
void   cash_truck_info__init
                     (CashTruckInfo         *message);
size_t cash_truck_info__get_packed_size
                     (const CashTruckInfo   *message);
size_t cash_truck_info__pack
                     (const CashTruckInfo   *message,
                      uint8_t             *out);
size_t cash_truck_info__pack_to_buffer
                     (const CashTruckInfo   *message,
                      ProtobufCBuffer     *buffer);
CashTruckInfo *
       cash_truck_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cash_truck_info__free_unpacked
                     (CashTruckInfo *message,
                      ProtobufCAllocator *allocator);
/* AcceptCashTruck methods */
void   accept_cash_truck__init
                     (AcceptCashTruck         *message);
size_t accept_cash_truck__get_packed_size
                     (const AcceptCashTruck   *message);
size_t accept_cash_truck__pack
                     (const AcceptCashTruck   *message,
                      uint8_t             *out);
size_t accept_cash_truck__pack_to_buffer
                     (const AcceptCashTruck   *message,
                      ProtobufCBuffer     *buffer);
AcceptCashTruck *
       accept_cash_truck__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   accept_cash_truck__free_unpacked
                     (AcceptCashTruck *message,
                      ProtobufCAllocator *allocator);
/* UpDownCashTruck methods */
void   up_down_cash_truck__init
                     (UpDownCashTruck         *message);
size_t up_down_cash_truck__get_packed_size
                     (const UpDownCashTruck   *message);
size_t up_down_cash_truck__pack
                     (const UpDownCashTruck   *message,
                      uint8_t             *out);
size_t up_down_cash_truck__pack_to_buffer
                     (const UpDownCashTruck   *message,
                      ProtobufCBuffer     *buffer);
UpDownCashTruck *
       up_down_cash_truck__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   up_down_cash_truck__free_unpacked
                     (UpDownCashTruck *message,
                      ProtobufCAllocator *allocator);
/* ResAcceptCashTruck methods */
void   res_accept_cash_truck__init
                     (ResAcceptCashTruck         *message);
size_t res_accept_cash_truck__get_packed_size
                     (const ResAcceptCashTruck   *message);
size_t res_accept_cash_truck__pack
                     (const ResAcceptCashTruck   *message,
                      uint8_t             *out);
size_t res_accept_cash_truck__pack_to_buffer
                     (const ResAcceptCashTruck   *message,
                      ProtobufCBuffer     *buffer);
ResAcceptCashTruck *
       res_accept_cash_truck__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   res_accept_cash_truck__free_unpacked
                     (ResAcceptCashTruck *message,
                      ProtobufCAllocator *allocator);
/* TruckEndurance methods */
void   truck_endurance__init
                     (TruckEndurance         *message);
size_t truck_endurance__get_packed_size
                     (const TruckEndurance   *message);
size_t truck_endurance__pack
                     (const TruckEndurance   *message,
                      uint8_t             *out);
size_t truck_endurance__pack_to_buffer
                     (const TruckEndurance   *message,
                      ProtobufCBuffer     *buffer);
TruckEndurance *
       truck_endurance__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   truck_endurance__free_unpacked
                     (TruckEndurance *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*XunbaoPos_Closure)
                 (const XunbaoPos *message,
                  void *closure_data);
typedef void (*CashTruckInfo_Closure)
                 (const CashTruckInfo *message,
                  void *closure_data);
typedef void (*AcceptCashTruck_Closure)
                 (const AcceptCashTruck *message,
                  void *closure_data);
typedef void (*UpDownCashTruck_Closure)
                 (const UpDownCashTruck *message,
                  void *closure_data);
typedef void (*ResAcceptCashTruck_Closure)
                 (const ResAcceptCashTruck *message,
                  void *closure_data);
typedef void (*TruckEndurance_Closure)
                 (const TruckEndurance *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor xunbao_pos__descriptor;
extern const ProtobufCMessageDescriptor cash_truck_info__descriptor;
extern const ProtobufCMessageDescriptor accept_cash_truck__descriptor;
extern const ProtobufCMessageDescriptor up_down_cash_truck__descriptor;
extern const ProtobufCMessageDescriptor res_accept_cash_truck__descriptor;
extern const ProtobufCMessageDescriptor truck_endurance__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_xunbao_2eproto__INCLUDED */
