/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_yuqidao_2eproto__INCLUDED
#define PROTOBUF_C_yuqidao_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _YuqidaoMaiData YuqidaoMaiData;
typedef struct _YuqidaoBreakData YuqidaoBreakData;
typedef struct _YuqidaoInfoAnswer YuqidaoInfoAnswer;
typedef struct _YuqidaoFillRequest YuqidaoFillRequest;
typedef struct _YuqidaoFillAnswer YuqidaoFillAnswer;
typedef struct _YuqidaoBreakRequest YuqidaoBreakRequest;
typedef struct _YuqidaoBreakAnswer YuqidaoBreakAnswer;
typedef struct _YuqidaoBreakRetainRequest YuqidaoBreakRetainRequest;
typedef struct _YuqidaoBreakRetainAnswer YuqidaoBreakRetainAnswer;
typedef struct _YuqidaoMaiOpenNotify YuqidaoMaiOpenNotify;


/* --- enums --- */


/* --- messages --- */

struct  _YuqidaoMaiData
{
  ProtobufCMessage base;
  uint32_t maiid;
  uint32_t acupointid;
  uint32_t filllv;
};
#define YUQIDAO_MAI_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yuqidao_mai_data__descriptor) \
    , 0, 0, 0 }


struct  _YuqidaoBreakData
{
  ProtobufCMessage base;
  uint32_t id;
  size_t n_curattr;
  uint32_t *curattr;
  size_t n_newattr;
  uint32_t *newattr;
  size_t n_newaddn;
  uint32_t *newaddn;
};
#define YUQIDAO_BREAK_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yuqidao_break_data__descriptor) \
    , 0, 0,NULL, 0,NULL, 0,NULL }


struct  _YuqidaoInfoAnswer
{
  ProtobufCMessage base;
  uint32_t result;
  size_t n_mais;
  YuqidaoMaiData **mais;
  size_t n_breaks;
  YuqidaoBreakData **breaks;
};
#define YUQIDAO_INFO_ANSWER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yuqidao_info_answer__descriptor) \
    , 0, 0,NULL, 0,NULL }


struct  _YuqidaoFillRequest
{
  ProtobufCMessage base;
  uint32_t maiid;
};
#define YUQIDAO_FILL_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yuqidao_fill_request__descriptor) \
    , 0 }


struct  _YuqidaoFillAnswer
{
  ProtobufCMessage base;
  uint32_t result;
  uint32_t maiid;
  uint32_t acupointid;
  uint32_t filllv;
};
#define YUQIDAO_FILL_ANSWER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yuqidao_fill_answer__descriptor) \
    , 0, 0, 0, 0 }


struct  _YuqidaoBreakRequest
{
  ProtobufCMessage base;
  uint32_t breakid;
  uint32_t time;
};
#define YUQIDAO_BREAK_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yuqidao_break_request__descriptor) \
    , 0, 0 }


struct  _YuqidaoBreakAnswer
{
  ProtobufCMessage base;
  uint32_t result;
  YuqidaoBreakData *breakinfo;
};
#define YUQIDAO_BREAK_ANSWER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yuqidao_break_answer__descriptor) \
    , 0, NULL }


struct  _YuqidaoBreakRetainRequest
{
  ProtobufCMessage base;
  uint32_t breakid;
};
#define YUQIDAO_BREAK_RETAIN_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yuqidao_break_retain_request__descriptor) \
    , 0 }


struct  _YuqidaoBreakRetainAnswer
{
  ProtobufCMessage base;
  uint32_t result;
  YuqidaoBreakData *breakinfo;
};
#define YUQIDAO_BREAK_RETAIN_ANSWER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yuqidao_break_retain_answer__descriptor) \
    , 0, NULL }


struct  _YuqidaoMaiOpenNotify
{
  ProtobufCMessage base;
  size_t n_mais;
  YuqidaoMaiData **mais;
};
#define YUQIDAO_MAI_OPEN_NOTIFY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yuqidao_mai_open_notify__descriptor) \
    , 0,NULL }


/* YuqidaoMaiData methods */
void   yuqidao_mai_data__init
                     (YuqidaoMaiData         *message);
size_t yuqidao_mai_data__get_packed_size
                     (const YuqidaoMaiData   *message);
size_t yuqidao_mai_data__pack
                     (const YuqidaoMaiData   *message,
                      uint8_t             *out);
size_t yuqidao_mai_data__pack_to_buffer
                     (const YuqidaoMaiData   *message,
                      ProtobufCBuffer     *buffer);
YuqidaoMaiData *
       yuqidao_mai_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yuqidao_mai_data__free_unpacked
                     (YuqidaoMaiData *message,
                      ProtobufCAllocator *allocator);
/* YuqidaoBreakData methods */
void   yuqidao_break_data__init
                     (YuqidaoBreakData         *message);
size_t yuqidao_break_data__get_packed_size
                     (const YuqidaoBreakData   *message);
size_t yuqidao_break_data__pack
                     (const YuqidaoBreakData   *message,
                      uint8_t             *out);
size_t yuqidao_break_data__pack_to_buffer
                     (const YuqidaoBreakData   *message,
                      ProtobufCBuffer     *buffer);
YuqidaoBreakData *
       yuqidao_break_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yuqidao_break_data__free_unpacked
                     (YuqidaoBreakData *message,
                      ProtobufCAllocator *allocator);
/* YuqidaoInfoAnswer methods */
void   yuqidao_info_answer__init
                     (YuqidaoInfoAnswer         *message);
size_t yuqidao_info_answer__get_packed_size
                     (const YuqidaoInfoAnswer   *message);
size_t yuqidao_info_answer__pack
                     (const YuqidaoInfoAnswer   *message,
                      uint8_t             *out);
size_t yuqidao_info_answer__pack_to_buffer
                     (const YuqidaoInfoAnswer   *message,
                      ProtobufCBuffer     *buffer);
YuqidaoInfoAnswer *
       yuqidao_info_answer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yuqidao_info_answer__free_unpacked
                     (YuqidaoInfoAnswer *message,
                      ProtobufCAllocator *allocator);
/* YuqidaoFillRequest methods */
void   yuqidao_fill_request__init
                     (YuqidaoFillRequest         *message);
size_t yuqidao_fill_request__get_packed_size
                     (const YuqidaoFillRequest   *message);
size_t yuqidao_fill_request__pack
                     (const YuqidaoFillRequest   *message,
                      uint8_t             *out);
size_t yuqidao_fill_request__pack_to_buffer
                     (const YuqidaoFillRequest   *message,
                      ProtobufCBuffer     *buffer);
YuqidaoFillRequest *
       yuqidao_fill_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yuqidao_fill_request__free_unpacked
                     (YuqidaoFillRequest *message,
                      ProtobufCAllocator *allocator);
/* YuqidaoFillAnswer methods */
void   yuqidao_fill_answer__init
                     (YuqidaoFillAnswer         *message);
size_t yuqidao_fill_answer__get_packed_size
                     (const YuqidaoFillAnswer   *message);
size_t yuqidao_fill_answer__pack
                     (const YuqidaoFillAnswer   *message,
                      uint8_t             *out);
size_t yuqidao_fill_answer__pack_to_buffer
                     (const YuqidaoFillAnswer   *message,
                      ProtobufCBuffer     *buffer);
YuqidaoFillAnswer *
       yuqidao_fill_answer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yuqidao_fill_answer__free_unpacked
                     (YuqidaoFillAnswer *message,
                      ProtobufCAllocator *allocator);
/* YuqidaoBreakRequest methods */
void   yuqidao_break_request__init
                     (YuqidaoBreakRequest         *message);
size_t yuqidao_break_request__get_packed_size
                     (const YuqidaoBreakRequest   *message);
size_t yuqidao_break_request__pack
                     (const YuqidaoBreakRequest   *message,
                      uint8_t             *out);
size_t yuqidao_break_request__pack_to_buffer
                     (const YuqidaoBreakRequest   *message,
                      ProtobufCBuffer     *buffer);
YuqidaoBreakRequest *
       yuqidao_break_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yuqidao_break_request__free_unpacked
                     (YuqidaoBreakRequest *message,
                      ProtobufCAllocator *allocator);
/* YuqidaoBreakAnswer methods */
void   yuqidao_break_answer__init
                     (YuqidaoBreakAnswer         *message);
size_t yuqidao_break_answer__get_packed_size
                     (const YuqidaoBreakAnswer   *message);
size_t yuqidao_break_answer__pack
                     (const YuqidaoBreakAnswer   *message,
                      uint8_t             *out);
size_t yuqidao_break_answer__pack_to_buffer
                     (const YuqidaoBreakAnswer   *message,
                      ProtobufCBuffer     *buffer);
YuqidaoBreakAnswer *
       yuqidao_break_answer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yuqidao_break_answer__free_unpacked
                     (YuqidaoBreakAnswer *message,
                      ProtobufCAllocator *allocator);
/* YuqidaoBreakRetainRequest methods */
void   yuqidao_break_retain_request__init
                     (YuqidaoBreakRetainRequest         *message);
size_t yuqidao_break_retain_request__get_packed_size
                     (const YuqidaoBreakRetainRequest   *message);
size_t yuqidao_break_retain_request__pack
                     (const YuqidaoBreakRetainRequest   *message,
                      uint8_t             *out);
size_t yuqidao_break_retain_request__pack_to_buffer
                     (const YuqidaoBreakRetainRequest   *message,
                      ProtobufCBuffer     *buffer);
YuqidaoBreakRetainRequest *
       yuqidao_break_retain_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yuqidao_break_retain_request__free_unpacked
                     (YuqidaoBreakRetainRequest *message,
                      ProtobufCAllocator *allocator);
/* YuqidaoBreakRetainAnswer methods */
void   yuqidao_break_retain_answer__init
                     (YuqidaoBreakRetainAnswer         *message);
size_t yuqidao_break_retain_answer__get_packed_size
                     (const YuqidaoBreakRetainAnswer   *message);
size_t yuqidao_break_retain_answer__pack
                     (const YuqidaoBreakRetainAnswer   *message,
                      uint8_t             *out);
size_t yuqidao_break_retain_answer__pack_to_buffer
                     (const YuqidaoBreakRetainAnswer   *message,
                      ProtobufCBuffer     *buffer);
YuqidaoBreakRetainAnswer *
       yuqidao_break_retain_answer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yuqidao_break_retain_answer__free_unpacked
                     (YuqidaoBreakRetainAnswer *message,
                      ProtobufCAllocator *allocator);
/* YuqidaoMaiOpenNotify methods */
void   yuqidao_mai_open_notify__init
                     (YuqidaoMaiOpenNotify         *message);
size_t yuqidao_mai_open_notify__get_packed_size
                     (const YuqidaoMaiOpenNotify   *message);
size_t yuqidao_mai_open_notify__pack
                     (const YuqidaoMaiOpenNotify   *message,
                      uint8_t             *out);
size_t yuqidao_mai_open_notify__pack_to_buffer
                     (const YuqidaoMaiOpenNotify   *message,
                      ProtobufCBuffer     *buffer);
YuqidaoMaiOpenNotify *
       yuqidao_mai_open_notify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yuqidao_mai_open_notify__free_unpacked
                     (YuqidaoMaiOpenNotify *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*YuqidaoMaiData_Closure)
                 (const YuqidaoMaiData *message,
                  void *closure_data);
typedef void (*YuqidaoBreakData_Closure)
                 (const YuqidaoBreakData *message,
                  void *closure_data);
typedef void (*YuqidaoInfoAnswer_Closure)
                 (const YuqidaoInfoAnswer *message,
                  void *closure_data);
typedef void (*YuqidaoFillRequest_Closure)
                 (const YuqidaoFillRequest *message,
                  void *closure_data);
typedef void (*YuqidaoFillAnswer_Closure)
                 (const YuqidaoFillAnswer *message,
                  void *closure_data);
typedef void (*YuqidaoBreakRequest_Closure)
                 (const YuqidaoBreakRequest *message,
                  void *closure_data);
typedef void (*YuqidaoBreakAnswer_Closure)
                 (const YuqidaoBreakAnswer *message,
                  void *closure_data);
typedef void (*YuqidaoBreakRetainRequest_Closure)
                 (const YuqidaoBreakRetainRequest *message,
                  void *closure_data);
typedef void (*YuqidaoBreakRetainAnswer_Closure)
                 (const YuqidaoBreakRetainAnswer *message,
                  void *closure_data);
typedef void (*YuqidaoMaiOpenNotify_Closure)
                 (const YuqidaoMaiOpenNotify *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor yuqidao_mai_data__descriptor;
extern const ProtobufCMessageDescriptor yuqidao_break_data__descriptor;
extern const ProtobufCMessageDescriptor yuqidao_info_answer__descriptor;
extern const ProtobufCMessageDescriptor yuqidao_fill_request__descriptor;
extern const ProtobufCMessageDescriptor yuqidao_fill_answer__descriptor;
extern const ProtobufCMessageDescriptor yuqidao_break_request__descriptor;
extern const ProtobufCMessageDescriptor yuqidao_break_answer__descriptor;
extern const ProtobufCMessageDescriptor yuqidao_break_retain_request__descriptor;
extern const ProtobufCMessageDescriptor yuqidao_break_retain_answer__descriptor;
extern const ProtobufCMessageDescriptor yuqidao_mai_open_notify__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_yuqidao_2eproto__INCLUDED */
